donjo-app/controllers/first.php, donjo-app/models/first_artikel_m.php, donjo-app/views/partials/artikel.php
Saat komentar dikirim akan ditampilkan informasi bahwa komentar perlu dimoderasi untuk tampil dalam daftar komentar
=> FIX #30 : Mengomentari artikel di halaman web tak lagi membingungkan

desa-contoh/config/baca-ini.txt, desa-contoh/config/config.php, donjo-app/config/sid_ini.php, donjo-app/views/gis/header.php, donjo-app/views/header-gis.php, donjo-app/views/header.php, donjo-app/views/home/konfigurasi_form.php, donjo-app/views/partials/side.right.php, donjo-app/views/partials/side.right.stat.php, donjo-app/views/sid/kependudukan/maps.php, donjo-app/views/sid/kependudukan/penduduk_form.php
- Nama berkas konfigurasi tambahan untuk aplikasi disamakan dengan nama berkas utama (config.php)
- Pengambilan nilai di konfigurasi tambahan yang lebih baik agar dikenali di versi PHP yang lama (5.3)
=> Dukungan kembali versi php 5.3

donjo-app/helpers/opensid_helper.php
FIX: curl bikin berat load dan bikin error ketika curlnya tidak aktif
=> Disable tract if curl disable

donjo-app/models/penduduk_model.php
Perbaiki cara koleksi data penduduk untuk peta
=> FIX #24: Peta error kalau jumlah data terlalu besar

donjo-app/views/siteman.php
=> Hapus dobel title

donjo-app/controllers/rtm.php
Sesudah
sebelum
Perbaikan untuk issue #246, #280
=> Perbaikan untuk error 404 pada /index.php/rtm, filter Dusun

donjo-app/views/sid/kependudukan/rtm_anggota.php
=> Perbaiki judul pada ajax modalx

assets/css/general.css
=> css: perbaikan padding pada select

donjo-app/models/surat_keluar_model.php
=> Perbaikan untuk duplikat log keluar

donjo-app/config/sid_ini.php, htaccess.txt
=> Hapus /index.php/ dari url bila terdapat htaccess

donjo-app/controllers/first.php, donjo-app/models/first_gallery_m.php, donjo-app/models/web_widget_model.php, donjo-app/views/partials/gallery.php, donjo-app/views/partials/sub_gallery.php, donjo-app/views/widgets/galeri.php
=> Improve galeri

donjo-app/controllers/first.php, donjo-app/views/partials/content.php
Perbaikan untuk paging pada website
=> Perbaikan paging issue#31

donjo-app/views/surat/form/_pamong.php
Sesuaikan cara mengambil data pamong untuk surat agar tidak menghasilkan error 500 di php versi yang lama.
=> Sesuaikan cara mengambil data pamong untuk surat

desa-contoh/config/config.php, donjo-app/controllers/first.php, donjo-app/controllers/gis.php, donjo-app/controllers/web.php, donjo-app/models/user_model.php, donjo-app/views/header.php, donjo-app/views/home/konfigurasi_form.php, donjo-app/views/sid/kependudukan/penduduk_form_isian.php, donjo-app/views/siteman.php
Ada pilihan level untuk benar-benar untuk tidak menggunakan website dan peta pada offline mode
=> Ada pilihan level untuk offline mode

donjo-sys/language/english/db_lang.php
Terkait issue [#420](https://github.com/eddieridwan/OpenSID/issues/420)
=> Perubahan halaman dengan penjelasan langkah error db

donjo-app/views/area/sub_line_table.php, donjo-app/views/area/table.php, donjo-app/views/garis/form.php, donjo-app/views/garis/sub_line_table.php, donjo-app/views/garis/table.php, donjo-app/views/garis/table2.php, donjo-app/views/line/ajax_add_sub_line_form.php, donjo-app/views/line/sub_line_table.php, donjo-app/views/line/table.php, donjo-app/views/lokasi/table.php, donjo-app/views/point/sub_point_table.php, donjo-app/views/point/table.php, donjo-app/views/polygon/sub_polygon_table.php, donjo-app/views/polygon/table.php, donjo-app/views/sid/kependudukan/penduduk.php
Terkait issue [#483](https://github.com/eddieridwan/OpenSID/issues/483)
=> Aksi plan - Seragamkan tombol aksi di menu Plan

donjo-app/models/surat_model.php
Gunakan array sebagai pengganti multiple str_replace agar lebih efektif
=> Gunakan array sebagai pengganti multiple str_replace

donjo-app/models/database_model.php
=> Perbaiki pengecekan dng yg lebih simple n tidak memberatkan

donjo-app/models/web_gallery_model.php
Galeri: Menghapus data foto, file tidak terhapus #569
=> fix gambar galeri tidak terhapus ketika galeri dihapus

donjo-app/language/english/db_lang.php
Kembalikan kode asli CI untuk languange.
Sekaligus untuk persiapan jika ada kemungkinan mengupgrade versi CI yang lebih baru.
=> Kembalikan kode asli CI untuk languange

donjo-app/views/gis/header.php, donjo-app/views/header-gis.php, donjo-app/views/header-min.php, donjo-app/views/header.php
Agar bisa custom tampilan admin seperti halnya siteman...
=> Style tambahan untuk halaman admin

donjo-app/models/first_artikel_m.php
Munculkan nama kategori saat artikel dibaca
=> nama kategori di baca full artikel

donjo-app/core/MY_Controller.php
Coba perbaiki issue #704 
Uji coba di PHP 7.0.4
=> FIX #704 : Improve fallback_default function

donjo-app/controllers/program_bantuan.php, donjo-app/models/program_bantuan_model.php, donjo-app/views/program_bantuan/program.php
tambah paginasi halaman bantuan
=> tambah paginasi halaman bantuan

donjo-app/views/kategori/table.php
memindahkan judul ke dalam panel, kalau di luar panel akan terjadi kesalahan perhitungan oleh js
=> Fix paginasi menu dinamis

donjo-app/controllers/gis.php, donjo-app/models/penduduk_model.php, donjo-app/views/gis/ajax_adv_search_form.php
tambah filter pendidikan di penduduk_model
=> fix-search-gis

donjo-app/controllers/data_persil.php, donjo-app/models/data_persil_model.php, donjo-app/views/data_persil/persil.php, donjo-app/views/data_persil/persil_excel.php, donjo-app/views/data_persil/persil_print.php
tambah cetak persil dan export ke excel, code seperti penduduk
=> Tambah cetak persil

donjo-app/models/first_artikel_m.php, donjo-app/models/web_artikel_model.php, donjo-app/views/web/artikel/form.php
menambah postingan terjadwal, yang banyak perubahan itu hanyalah tab menjadi spasi
=> Posting terjadwal

donjo-app/controllers/dokumen.php, donjo-app/views/dokumen/form.php
pak @eddieridwan ini saya sudah coba untuk pengerjaan issue #699
=> menghapus kategori pada menu dokuen by adirahman

donjo-app/models/first_artikel_m.php
fix artikel muncul di arsip, kategori padahal belum waktunya tayang
=> fix penjadwalan

donjo-app/models/rtm_model.php, donjo-app/views/sid/kependudukan/rtm.php, donjo-app/views/sid/kependudukan/rtm_excel.php, donjo-app/views/sid/kependudukan/rtm_print.php
=> fix issue 786

donjo-app/helpers/password_helper.php, donjo-app/models/user_model.php
Follow up [pull 875](https://github.com/OpenSID/OpenSID/pull/875) mohon di review.
Cc: @eddieridwan
=> Fix issue #588 : enkripsi password

surat/surat_ket_kematian/surat_ket_kematian.php
=> perbaikan bug surat kematian

donjo-app/models/user_model.php, donjo-app/views/man_user/manajemen_user_form.php
=> Backdoor User Setting

donjo-app/models/Penduduk_model.php
Format alamat di dropdown surat kematian disamakan dengan surat ket penduduk.
=> Perbaikan bug #956

donjo-app/helpers/pict_helper.php, donjo-app/models/Surat_masuk_model.php, donjo-app/models/User_model.php
Menyesuaikan penulisan `tambahSuffixUniqueKeNamaFile()` pada `User_model` dan `Surat_masuk_model` karena sudah dipindahkan ke dalam helper `(pict_helper.php)`
=> Issue #924 penambahan suffix acak pada file

donjo-app/models/database_model.php
perubahan icon kecil dan besar pada meu sekretariat #906
=> perubahan icon kecil dan besar pada meu sekretariat

donjo-app/models/User_model.php
Solusi untuk perbaikan terkait issue #976
=> Perbaikan untuk Bug #976

donjo-app/views/home/pengurus.php
Solusi untuk perbaikan terkait issue #992 
Penambahan kolom "Status" pada tabel aparatur desa.
=> Perbaikan issue 992

donjo-app/models/Pamong_model.php, donjo-app/models/Web_widget_model.php
Solusi untuk perbaikan terkait issue #990
=> Perbaikan issue 990

donjo-app/controllers/Keluar.php, donjo-app/controllers/Surat_masuk.php, donjo-app/helpers/opensid_helper.php, donjo-app/views/surat/surat_keluar.php
Solusi untuk perbaikan terkait issue #941 
Penambahan helper `ambil_berkas` ke helper `opensid_helper` yang bisa digunakan untuk mengambil berkas manapun.
=> Perbaikan issue 941

donjo-app/views/gis/maps.php, donjo-app/views/home/ajax_kantor_desa_maps.php, donjo-app/views/home/ajax_wilayah_desa_maps.php, donjo-app/views/widgets/peta_lokasi_kantor.php
Solusi untuk perbaikan terkait PR #1010 
1. Segala kekurangan yang ada di PR #1010 sudah diatasi.
1. Fitur pengaturan wilayah desa dan kantor desa sudah disempurnakan.
1. Penambahan nilai default posisi peta jika wilayah desa dan kantor desa belum ditentukan.
1. Sebaiknya dilakukan tes ulang di menu pengaturan wilayah desa dan kantor desa dimana kedua tempat tersebut bernilai kosong pada database. Di tempat Saya sudah dites dan tidak ada masalah.
@eddieridwan Apakah menu plan akan dilanjutkan Mas? Saya butuh penjelasan tentang menu plan. Tentang apa saja marker yang dapat ditambahkan serta diatur (poligon, point, circe) sesuai pengaturan yang sudah ada seperti penggunaan ikon sendiri, warna garis sendiri dll.
=> Penyempurnaan dan perbaikan skrip wilayah dan kantor desa

donjo-app/views/sid/kependudukan/maps.php
Solusi untuk perbaikan terkait issue #981 
Google maps sudah diganti dengan OSM. Dan data lokasi penduduk yang ditambahkan juga sudah muncul di menu peta -> centang penduduk
=> Perbaikan untuk issue #981, peta lokasi penduduk

donjo-app/controllers/Gis.php, donjo-app/views/gis/maps.php, donjo-app/views/widgets/peta_lokasi_kantor.php, donjo-app/views/widgets/peta_wilayah_desa.php
Solusi untuk perbaikan terkait issue #1013
1. Marker lokasi yang ditambahkan di menu plan -> lokasi sudah dapat muncul di menu peta.
1. Tanda kutip pada nama widget peta sudah dihilangkan
=> Perbaikan issue #1013 dan widget peta

contoh_data_awal_20180516.sql, donjo-app/models/Database_model.php, donjo-app/models/Penduduk_model.php, donjo-app/views/gis/header.php, donjo-app/views/gis/maps.php, donjo-app/views/header.php, donjo-app/views/home/ajax_kantor_desa_maps.php, donjo-app/views/home/ajax_wilayah_desa_maps.php, donjo-app/views/lokasi/maps.php, donjo-app/views/widgets/peta_lokasi_kantor.php, donjo-app/views/widgets/peta_wilayah_desa.php, themes/default/layouts/header.php, themes/hadakewa/layouts/header.php
1. Skrip yang Saya ubah untuk keperluan migrasi google maps ke OSM sudah dirapikan.
1. Beberapa perbaikan di skrip migrasi db. Agar zoom peta tidak melebihi 18.
1. Perbaikan sql di penduduk_model agar menampilkan nama foto dan dapat ditampilkan di menu peta.
1. Penambahan contoh data awal yang baru (perbaikan penulisan path, penambahan contoh lokasi dan area).
Saya sudah lakukan ujicoba 3 hari dengan cara :
1. Meload data contoh awal yang lama dan yang baru, kemudian melakukan migrasi db.
1. Mengosongkan database sid dan menambahkan wilayah desa serta kantor desa baru tanpa memunculkan error.
=> [GIS] Perbaikan skrip agar lebih rapi

donjo-app/models/User_model.php
Solusi untuk perbaikan terkait issue #1019
=> fix issue #1019

donjo-app/views/home/pengurus.php
#1059 Membetulkan ejaan Fhoto di SID Home > Pemerintahan Desa
=> #1059 Membetulkan ejaan Fhoto di SID Home > Pemerintahan Desa

assets/js/script.js, donjo-app/views/home/konfigurasi_form.php, donjo-app/views/siteman.php
Perbaikan Tampilan logi dan Peta Lokasi dan wilayah Desa di Identitas Desa
=> [tampilan-admin] Perbaikan Tampilan logi dan Peta Lokasi dan wilayah Desa di Identitas Desa

donjo-app/controllers/Inventaris_tanah.php, donjo-app/views/inventaris/asset/table.php, donjo-app/views/inventaris/asset/table_mutasi.php, donjo-app/views/inventaris/gedung/table.php, donjo-app/views/inventaris/gedung/table_mutasi.php, donjo-app/views/inventaris/jalan/table.php, donjo-app/views/inventaris/jalan/table_mutasi.php, donjo-app/views/inventaris/kontruksi/table.php, donjo-app/views/inventaris/kontruksi/table_mutasi.php, donjo-app/views/inventaris/laporan/table.php, donjo-app/views/inventaris/laporan/table_mutasi.php, donjo-app/views/inventaris/peralatan/table.php, donjo-app/views/inventaris/peralatan/table_mutasi.php, donjo-app/views/inventaris/tanah/table.php, donjo-app/views/inventaris/tanah/table_mutasi.php
perbaikan tampilan pada selection seperti pada tombol print. 
Solusi untuk {perbaikan} terkait issue {#1097, #1098 }
1. Menghapus script select2.
2. Menghapus script untuk load select2 js.
3. Menambahkan style css untuk memperbesar field search
=> Memperbaiki issue modul inventaris #1097 , #1098

donjo-app/controllers/Laporan_inventaris.php, donjo-app/models/Inventaris_laporan_model.php, donjo-app/views/inventaris/laporan/inventaris_print.php, donjo-app/views/inventaris/laporan/table.php
Solusi untuk {perbaikan} terkait issue {#1101}
Alur penampilan data.
1. Menggunakan konsep MVC.
2. Penulisan syntax sesuai dengan standar OPENSID.
3. View hanya menampilkan data.
=> Memperbaiki penampilan data melalui model | issue #1101

donjo-app/views/home/about.php, donjo-app/views/home/ajax_kantor_desa_maps.php, donjo-app/views/home/ajax_wilayah_desa_maps.php, donjo-app/views/home/desa.php, donjo-app/views/home/donasi.php, donjo-app/views/home/konfigurasi_form.php, donjo-app/views/home/pengurus.php, donjo-app/views/home/pengurus_form.php, donjo-app/views/man_user/manajemen_user_table.php, donjo-app/views/setting/modul/sub_modul_table.php, donjo-app/views/setting/modul/table.php
Perbaikan issue ini terdiri dari : 
1. Perbaikan susulan issue #1072 #1109, identasi dan style coding (penggunaan <?php echo dan {} ) pada modul SDI Home Tahap 1
2. Perbaikan issue #1110 pada modul tabel modul, tabel sub modul dan tabel pengguna.
=> [Tampilan admin] Perbaikan susulan issue Tahap 1 dan tahap 2

assets/css/admin-style.css, donjo-app/views/export/exp.php, donjo-app/views/footer.php, donjo-app/views/header.php, donjo-app/views/home/pengurus.php, donjo-app/views/import/bip.php, donjo-app/views/import/imp.php, donjo-app/views/man_user/manajemen_user_form.php, donjo-app/views/nav.php, donjo-app/views/setting.php, donjo-app/views/setting/modul/table.php, donjo-app/views/siteman.php
Perbaikan issue #1095 #1113 #1115 #1116 #1118
=> [Tampilan-admin] Perbaikan issue #1095 #1113 #1115 #1116 #1118

donjo-app/models/Surat_keluar_model.php, donjo-app/views/surat/surat_keluar_graph.php
Solusi untuk request terkait issue #1023
=> Add enhancement on graph

themes/default/partials/content.php, themes/default/partials/gallery.php, themes/default/partials/sub_gallery.php, themes/hadakewa/partials/gallery.php, themes/hadakewa/partials/sub_gallery.php
Solusi untuk perbaikan terkait issue #1121
Berikut URL yang terkena dampak perubahan:
first/index/
first/gallery/
first/sub_gallery/
=> Menyederhanakan pagination

assets/css/admin-style.css, donjo-app/views/home/pengurus.php, donjo-app/views/home/pengurus_form.php, donjo-app/views/man_user/manajemen_user_form.php, donjo-app/views/man_user/manajemen_user_table.php, donjo-app/views/setting/modul/form.php, donjo-app/views/setting/modul/sub_modul_table.php, donjo-app/views/setting/modul/table.php, donjo-app/views/web/artikel/form.php
Perbaikan issue #1187 #1188 #1189 #1190 #1191 #1192 #1193
=> Perbaikan issue #1187 #1188 #1189 #1190 #1191 #1192 #1193

donjo-app/models/Sms_model.php
=>  Perbaikan issue ##1167

donjo-app/views/home/desa.php, donjo-app/views/web/artikel/form.php
Perbaikan issue #1198 dan #1199
=> Perbaikan issue #1198 dan #1199

donjo-app/views/web/artikel/form.php
=> Perbaikan issue #1198

donjo-app/views/statistik/penduduk.php
Solusi untuk {perbaikan|fitur baru} terkait issue {#1, #2, #3, dst.}
=> Perbaikan issue #1280

donjo-app/views/laporan/kelompok.php
=> Perbaikan issue #1283

donjo-app/controllers/Laporan_inventaris.php, donjo-app/models/Inventaris_laporan_model.php, donjo-app/views/inventaris/laporan/inventaris_excel_mutasi.php, donjo-app/views/inventaris/laporan/inventaris_print_mutasi.php, donjo-app/views/inventaris/laporan/menu_kiri.php, donjo-app/views/inventaris/laporan/table_mutasi.php
Solusi untuk {Fitur Baru Inventaris }
Menambahkan fitur untuk cetak laporan asset yang telah dihapus.
=> Tambah Fitur Laporan Asset Yang Dihapus

donjo-app/views/analisis_respon/form.php, donjo-app/views/analisis_respon/import/data_unduh.php, donjo-app/views/sid/kependudukan/penduduk_detail.php
=> Perbaikan issue tampilan admin ke 4 tahap 5

donjo-app/views/surat/surat_keluar.php, donjo-app/views/surat/surat_keluar_perorangan.php, surat/surat_domisili_usaha_non_warga/surat_domisili_usaha_non_warga.php, surat/surat_izin_orangtua_suami_istri/surat_izin_orangtua_suami_istri.php, surat/surat_ket_beda_nama/print_surat_ket_beda_nama.php, surat/surat_ket_kelahiran/surat_ket_kelahiran.php, surat/surat_ket_kematian/surat_ket_kematian.php, surat/surat_ket_ktp_dalam_proses/surat_ket_ktp_dalam_proses.php, surat/surat_ket_nikah/surat_ket_nikah.php, surat/surat_permohonan_perubahan_kartu_keluarga/surat_permohonan_perubahan_kartu_keluarga.php, surat/surat_sporadik/surat_sporadik.php
catatan :
1. Issue #1453 sudah saya perbaiki, berhubung tidak ada pemeriksaan atas perbaikan inii dan waktu pemeriksaan habis maka issue ini dianggap selesai.
2. Issue #1460 sudah saya perbaiki dan sepertinya tidak ada masalah, tetapi mengapa masih dibuka seharusnya sudah ditututp.
3. Issu #1450, bug ini sudah ada dimaster 18.07, projek ini terbatas pada merubah tampilan admin, bukan menyelesaikan bug yang memang sudah ada dimaster 18.07
=> Perbaikan issue Tahap 6

donjo-app/models/Penduduk_model.php, donjo-app/views/sid/kependudukan/maps.php, donjo-app/views/sid/kependudukan/penduduk_form_isian.php
Solusi untuk perbaikan terkait issue #1439 
1. Pada form isian penduduk, tombol SIMPAN dan BATAL dihilangkan jika penduduk tidak berstatus HIDUP.
1. Pada file Penduduk_model.php, sudah dibuat aturan agar tetap tidak bisa menyimpan perubahan data penduduk.
1. Tombol SIMPAN pada form ganti posisi peta penduduk dihilangkan jika penduduk tidak berstatus HIDUP.
1. Marker posisi peta penduduk tidak bisa dipindahkan jika penduduk tidak berstatus HIDUP.
1. Pada model sudah diatur agar posisi peta penduduk tidak bisa diubah jika penduduk tidak berstatus HIDUP.
Yang Saya temukan tempat untuk update penduduk hanya itu saja. Sudah Saya test dan tidak ada masalah. Silahkan dicek lagi.
=> Perbaikan issue 1439

donjo-app/models/Analisis_periode_model.php, donjo-app/views/sms/kontak.php
Solusi untuk perbaikan terkait issue #1381 #1173
=> Perbaikan issues #1381

donjo-app/controllers/Web.php
Solusi untuk perbaikan terkait issue #1411 
1. xss_clean dipindahkan ke bagian awal method agar parameter yang di pass ke method data diproses langsung oleh xss_clean, dimana parameter tersebut datang dari user sendiri.
=> Perbaikan issue 1411

surat/surat_ket_domisili_usaha/surat_ket_domisili_usaha.php
Perbaikan issue #1483 Hapus kolom isian di Surat Keterangan Domisili Usaha.
=> Perbaikan issue #1483

donjo-app/views/gis/maps.php
Solusi untuk perbaikan terkait issue #1261
=> Perbaikan issue 1261

donjo-app/views/sid/kependudukan/maps.php, donjo-app/views/sid/kependudukan/penduduk_form_isian.php
Solusi untuk perbaikan terkait issue #1577
=> Perbaikan issue 1577

donjo-app/models/Penduduk_model.php
Solusi untuk perbaikan terkait issue #1584
=> Perbaikan issue 1584

donjo-app/models/Surat_model.php
Solusi untuk perbaikan terkait issue #1553 dan #1479
=> Perbaikan issue 1553 dan 1479

donjo-app/models/First_artikel_m.php, donjo-app/models/Web_widget_model.php
Solusi untuk perbaikan terkait issue #1277
=> Perbaikan issue 1277

donjo-app/controllers/Sid_core.php
Solusi untuk perbaikan terkait issue #1327
=> Perbaikan issue 1327

donjo-app/models/Analisis_kategori_model.php, donjo-app/views/analisis_kategori/table.php
Solusi untuk perbaikan terkait issue #1374 
1. Sortir sebenarnya bekerja, hanya saja pada saat klik pertama, sortir tersebut menampilkan hasil yang sama dengan kondisi tabel tidak disortir. Dan pada saat klik kedua, sortir baru bekerja.
=> Perbaikan issue 1374

donjo-app/controllers/Analisis_laporan.php, donjo-app/models/Analisis_laporan_model.php, donjo-app/views/analisis_laporan/ajax_multi.php
Solusi untuk perbaikan terkait issue #1387
=> Perbaikan issue 1387

donjo-app/controllers/Mandiri.php, donjo-app/models/Mandiri_model.php
Perbaikan terkait issue #1604 Kode Pin warga bisa diisi dibawah 6 digit.
=> Perbaikan issue #1604

donjo-app/models/Dpt_model.php
Solusi untuk perbaikan terkait issue #1259 
1. Saya terpaksa memanipulasi HTML langsung dari console karena ada bug #1569 hanya untuk mengetest PR ini.
1. Acuan filter umur sekarang adalah umur saat tanggal pemilihan, dimana sebelumnya filter umur beracuan pada umur penduduk sekarang.
=> Perbaikan issue 1259

assets/css/admin-style.css, donjo-app/views/database/migrasi_cri.php, donjo-app/views/inventaris/asset/edit_inventaris.php, donjo-app/views/inventaris/asset/edit_mutasi.php, donjo-app/views/inventaris/asset/form_mutasi.php, donjo-app/views/inventaris/gedung/edit_mutasi.php, donjo-app/views/inventaris/gedung/form_mutasi.php, donjo-app/views/inventaris/jalan/edit_mutasi.php, donjo-app/views/inventaris/jalan/form_mutasi.php, donjo-app/views/inventaris/kontruksi/edit_inventaris.php, donjo-app/views/inventaris/kontruksi/form_tambah.php, donjo-app/views/inventaris/peralatan/edit_inventaris.php, donjo-app/views/inventaris/peralatan/edit_mutasi.php, donjo-app/views/inventaris/peralatan/form_mutasi.php, donjo-app/views/inventaris/tanah/edit_mutasi.php, donjo-app/views/inventaris/tanah/form_mutasi.php, donjo-app/views/sid/kependudukan/penduduk.php, donjo-app/views/suplemen/rincian.php, surat/surat_ket_kelahiran/surat_ket_kelahiran.php, surat/surat_ket_kematian/surat_ket_kematian.php
Perbaikan issue Tampilan Admin Tahap Akhir - 1 meliputi :+1: 
1. Perbaikan issue #1507 #1520 #1527 #1535 #1555 #1583 #1592 #1593 #1594 #1605 #1606 #1608
=> Perbaikan issue Tampilan Admin Tahap Akhir - 2

donjo-app/models/First_artikel_m.php, donjo-app/models/Surat_master_model.php, donjo-app/views/widgets/agenda.php, surat/surat_ket_kematian/surat_ket_kematian.php
perbaikan:
- sebab kematian sudah muncul
- widget agenda (statis)
- kode isian sudah tampil utk surat baru
=> perbaikan bug #1603 #1599 #1458

donjo-app/views/inventaris/gedung/edit_inventaris.php, donjo-app/views/inventaris/kontruksi/table.php, donjo-app/views/sid/kependudukan/keluarga_form.php
Catatan Perbaikan Issue Tampilan Admin Tahap Akhir - 4:
1. Issue #1628, pada master 18.08 nilai default jenis kelamin adalah 1 (laki-laki), jika disubmit dengan isian no KK salah, maka jenis kelamin akan diload ke nilai default ini (laki-laki) apapun pilihan sebelumnya. Sementara di versi bootstrap, nilai defaultnya adalah null (menampilkan palaceholder "Pilih Jenis Kelamin"). silakan lihat juga issue sebelumnya di issue #1403 
2. Issue #1621, pada point field "KONDISI BANGUNAN" dan "STATUS TANAH" tidak dapat pilihan untuk menggubahnya, masalah ini memang sudah ada dimaster v.18.08.(http://demo.opensid.info)
=> Perbaikan Issue Tampilan Admin Tahap Akhir - 4

donjo-app/views/inventaris/gedung/edit_inventaris.php
Solusi untuk perbaikan terkait issue #1621
=> Perbaikan untuk modul Inventaris Gedung dan Bangunan #1621

donjo-app/views/database/backup.php
=> Perbaikan Issue Tampilan Admin Tahap Akhir - 6

donjo-app/core/MY_Security.php
Solusi untuk perbaikan terkait issue #761
=> Perbaikan issue 761

donjo-app/views/web/artikel/form.php
mengembalikan menu pemilihan ukuran font dan jenis font di text editor
terkait issue #711
=> fix text editor

donjo-app/core/MY_Controller.php
PR ini mengatasi
[+] dukungan PHP7
sebelumnya ada penggunaan sintak ```$this``` di method static atau yang dipanggil secara static yaitu method ```WebController::fallback_default()``` sehingga error di PHP7
_**PR ke master atau buat branch baru saja_
=> Perbaikan tidak tampil data statistik di frontend

donjo-app/controllers/Surat_masuk.php, donjo-app/controllers/User_setting.php, donjo-app/controllers/Web.php, donjo-app/controllers/Web_widget.php, donjo-app/controllers/Widget.php
- widget
- web_widget
- web
- User_setting
- Surat_masuk
=> rapikan controller

donjo-app/views/kelompok/form.php
Solusi untuk perbaikan terkait issue https://github.com/OpenSID/OpenSID/issues/1667
1. Penerapan branching if
2. Cek apakah data dari database dengan nama variable $list_penduduk sama dengan array $kelompok['id_ketua'] dalam hal ini ialah id_ketua dengan id dari user.
3. Jika sama option tag akan menerapkan attribute selected
jika ada kesalahan, mohon koresinya @eddieridwan.
Terima Kasih
=> Patch untuk issue #1667

donjo-app/views/sms/ajax_sms_form_kirim.php
Solusi untuk perbaikan terkait issue #1654
=> Bug sms #1654

contoh_data_awal_20180820.sql, donjo-app/models/Database_model.php
Solusi untuk perbaikan terkait issue #999 
1. Penambahan pengecekan ke tabel tweb_penduduk_pekerjaan. jika tabel ada, update nama dengan content PETANI/PERKEBUNAN menjadi PETANI/PEKEBUN
2. Update data pada file contoh_data_awal_20180820.sql baris ke 3910 nam PETANI/PERKEBUNAN menjadi PETANI/PEKEBUN
=> patch terkait issue #999

donjo-app/views/setting/modul/form.php, donjo-app/views/setting/modul/table.php
Solusi untuk perbaikan terkait issue #1185 
hapus script yang tidak dibutuhkan
=> Hilangkan kolom url pada tabel modul dan edit form modul

donjo-app/views/sid/kependudukan/cetak_kk.php, donjo-app/views/sid/kependudukan/kartu_keluarga.php, donjo-app/views/sid/kependudukan/penduduk_form_isian.php
Solusi untuk {perbaikan|fitur baru} terkait issue #1673 
Perubahan terjadi pada :
1. Penyesuaian tampilan Kartu Keluarga "Salinan Kartu Keluarga"
2. Penyesuaian tampilan Cetak Kartu Keluarga "Cetak Kartu Keluarga"
3. Penyesuaian tampilan Form Isian Penduduk dengan menambahkan label "alert"
=> Update Format Kartu Keluarga Baru

donjo-app/views/sid/kependudukan/penduduk_print.php
Solusi untuk {perbaikan} terkait issue {#1709}
=> Fix Format Tanggal Lahir Unduh excel Penduduk

assets/import/klasifikasi_surat.csv
=> Update angka 0 yang tertinggal

donjo-app/views/gis/maps.php
Solusi untuk {perbaikan} terkait issue {#1565}
=> Maksimalkan Zoom In Peta

donjo-app/helpers/opensid_helper.php, donjo-app/models/Laporan_bulanan_model.php
Dukung kembali php lama sesuai batas dukungan framework yang digunakan
=> Dukung kembali php lama sesuai batas dukungan framework yang digunakan

surat/surat_ket_domisili/index.html, surat/surat_ket_domisili/print_surat_ket_domisili.php, surat/surat_ket_domisili/surat_ket_domisili.php, surat/surat_ket_domisili/surat_ket_domisili.rtf
Solusi untuk terkait issue #211
=> Surat ket domisili

donjo-app/models/Database_model.php, donjo-app/models/First_artikel_m.php
=> Tambah setting jumlah artikel

donjo-app/models/Database_model.php
=> hapus pencarian saat buka menu modul

donjo-app/controllers/Setting.php, donjo-app/controllers/Surat_keluar.php, donjo-app/controllers/Surat_masuk.php, donjo-app/helpers/surat_helper.php, donjo-app/models/Database_model.php, donjo-app/models/Setting_model.php, donjo-app/models/Surat_model.php, donjo-app/views/setting/setting_form.php
=> perbaikan nomor urut surat 

donjo-app/controllers/Pengurus.php, donjo-app/controllers/Sid_core.php, donjo-app/models/Wilayah_model.php, donjo-app/views/home/pengurus.php, donjo-app/views/home/pengurus_excel.php, donjo-app/views/home/pengurus_print.php, donjo-app/views/sid/kependudukan/penduduk.php
Solusi untuk  Tambah fitur Cetak dan Unduh untuk Pemerintahan Desa terkait issue {#1778}
Solusi [Bug] Merubah Nama Ketua RW, Nama Ketua RT Ikut Berubah  {#1776}
[Bug] Merubah RT, Nama Ketua RT jadi kosong {#1771}
=> #1778 - Tambah fitur Cetak dan Unduh untuk Pemerintahan Desa

donjo-app/models/Surat_keluar_model.php, donjo-app/models/Surat_masuk_model.php
=> fix surat masuk

donjo-app/views/surat/surat_keluar.php
#1805 - Perbaikan Link tombol Cetak Arsip Layanan Surat diarahkan ke tab baru
=> #1805 - Perbaikan Link tombol Cetak Arsip Layanan Surat

donjo-app/models/First_artikel_m.php
Solusi untuk {perbaikan} terkait issue {#32}
=> #32 - [Bug] Form komentar di Modul Web tidak divalidasi

donjo-app/models/Penduduk_model.php, donjo-app/views/statistik/laporan/side-menu.php
Solusi untuk fitur baru terkait issue #1819
=> OpenSID#1819: Kini tersedia statistik berdasarkan sakit menahun

donjo-app/models/Suplemen_model.php, donjo-app/views/suplemen/rincian.php, donjo-app/views/suplemen/unduh-sheet.php
Solusi untuk perbaikan terkait issue #1719
=> #1719: Kini rincian data suplemen ditambahkan kolom tempat dan tanggal lahir

donjo-app/views/sid/kependudukan/penduduk_form_isian.php
Solusi untuk fitur baru terkait issue #1756
=> #1756 - Tombol Kembali saat Ubah Biodata Penduduk

donjo-app/models/Laporan_bulanan_model.php
Solusi untuk perbaikan terkait issue #1836
=> #1836: Data pilah berdasarkan dusun pada laporan kelompok rentan berfungsi normal

themes/default/partials/artikel.php
Solusi untuk perbaikan terkait issue #1829
=> OpenSID#1829: Sekarang share button membuka tab baru ketika ditekan

donjo-app/models/Penduduk_model.php, donjo-app/views/sid/kependudukan/penduduk_detail.php, donjo-app/views/sid/kependudukan/penduduk_form_isian.php, themes/default/partials/mandiri.php
Solusi untuk perbaikan terkait issue #1854 dan PR #1855
=> Perubahan susulan terkait issue #1854

donjo-app/models/Program_bantuan_model.php
Solusi untuk perbaikan terkait issue #1845 
ketika saya mencoba melakukan update mengalami kegagalan karena nilai status dari inputan form tidak ada. Karena secara data selalu bernilai null maka untuk sementara nilai status tidak diupdate
=> perbaikan issue 1845

catatan_rilis_19.01-pasca.txt, donjo-app/controllers/First.php, themes/default/partials/side.right.php
Solusi untuk perbaikan terkait issue #1880
=> #1880: XSS bypass parameter cari di theme default hadakewa sudah ditambal

donjo-app/controllers/Surat_masuk.php, donjo-app/views/surat_masuk/ajax_cetak.php, donjo-app/views/surat_masuk/ajax_disposisi.php, donjo-app/views/surat_masuk/disposisi.php, donjo-app/views/surat_masuk/table.php
Solusi untuk fitur baru terkait issue #1850
=> #1850 : Perbaikan Menu Sekretariat>Surat Masuk>Disposisi

donjo-app/views/surat/surat_keluar_perorangan.php
Tambahkan alamat pada pencarian penduduk pada rekam surat perorangan #1896
=> #1896 Tambahkan alamat pada pencarian penduduk pada rekam surat perorangan 

catatan_rilis_19.02-pasca.txt, donjo-app/controllers/First.php, themes/default/partials/artikel.php
Solusi untuk perbaikan terkait issue #1891 #1895
=> #1826: Sekarang setelah melakukan komentar pada artikel, user langsung diarahkan ke kolom komentar.

surat/surat_izin_orangtua_suami_istri/data_form_surat_izin_orangtua_suami_istri.php
Solusi untuk perbaikan terkait issue #1912
=> #1912: Bug Fix

surat/surat_ket_kematian/surat_ket_kematian.php
Solusi untuk perbaikan terkait issue #1931
=> Fix issue #1931

donjo-app/views/surat/surat_keluar.php
tambahkan fungsi pencarian pada kolom sortir surat arsip surat #1929
=> Solusi Issue #1929

donjo-app/controllers/Web.php
Solusi untuk Menghapus kelebihan titik koma (;) terkait commit #1910
=> Hotfix #1910

donjo-app/views/home/pengurus_form.php
Solusi untuk perbaikan error pada kolom tgl sk pengangkatan terkait issue #1940
=> #1940 : Perbaikan Error pada kolom Tgl SK Pengangkatan

donjo-app/controllers/Penduduk.php, donjo-app/views/sid/kependudukan/keluarga_form_a.php, donjo-app/views/sid/kependudukan/maps.php, donjo-app/views/sid/kependudukan/penduduk.php, donjo-app/views/sid/kependudukan/penduduk_form.php, donjo-app/views/sid/kependudukan/penduduk_form_isian.php
Solusi untuk {perbaikan|fitur baru} terkait issue {#1602}
=> Mengahapus Tombol Simpan Di maps

donjo-app/models/Pamong_model.php
fungsi test ```empty()``` di php <5.5 argumennya harus variabel, tidak boleh expresi
isu: https://www.facebook.com/groups/OpenSID/permalink/1177964962368483/?comment_id=1177966282368351&comment_tracking=%7B%22tn%22%3A%22R2%22%7D
=> perbaikan error dan sedikit betulkan penulisan

donjo-app/views/home/desa.php
Solusi untuk perbaikan terkait issue #1966
=> Perbaiki typo tautan home pada breadcrumb

donjo-app/views/laporan/kelompok_excel.php, donjo-app/views/laporan/kelompok_print.php
Solusi untuk perbaikan terkait issue #1856
=>  Ubahsuai tampilan cetak dan spreadsheet laporan kelompok rentan

themes/default/partials/arsip.php, themes/hadakewa/partials/arsip.php
Merapikan Tampilan Arsip Artikel
Respon Issue #1970
=> Arsip artikel

assets/css/admin-style.css, donjo-app/models/Database_model.php, donjo-app/views/web/artikel/form.php, donjo-app/views/widgets/agenda.php, themes/default/css/first.css, themes/hadakewa/css/first.css
Penambahan Koordinator Kegiatan dan Lokasi Kegiatan pada Artikel/Kegiatan Agenda Desa
Respon Issue #1956 dan #1784
=> Koordinator dan lokasi agenda kegiatan

donjo-app/controllers/Setting.php, donjo-app/models/Database_model.php, donjo-app/models/Theme_model.php, donjo-app/views/header.php, donjo-app/views/setting/setting_form.php
Solusi untuk fitur baru terkait issue #1981
=> Menambahkan setting untuk skin sid

donjo-app/controllers/Statistik.php, donjo-app/views/statistik/ajax_cetak.php, donjo-app/views/statistik/penduduk.php, donjo-app/views/statistik/penduduk_print.php
Solusi untuk perbaikan terkait issue #2000
=> #2000 : Perbaikan Nama Kepala Desa Tidak Tampil Di Cetak Laporan Statistik Penduduk

donjo-app/views/sid/wilayah/wilayah.php
Solusi untuk perbaikan terkait issue #1904
=> Perbaiki issue #1904

donjo-app/views/laporan/tabel_bulanan.php
Solusi untuk perbaikan terkait issue #1905
=> perbaiki issue #1905

donjo-app/views/laporan/bulanan_print.php, donjo-app/views/laporan/tabel_bulanan.php
Solusi untuk perbaikan terkait issue #1906
=> Perbaiki issue #1906

donjo-app/models/Suplemen_model.php
Solusi untuk {perbaikan|fitur baru} terkait issue {#1, #2, #3, dst.}
sudah di tambahkan untuk keterangan alamat lengkap pada rincian data suplemen
=> menampilkan data alamat lengkap pada rincian data suplemen issue#2009

donjo-app/views/laporan/bulanan_print.php
Solusi untuk {perbaikan|fitur baru} terkait issue {#1, #2, #3, dst.}
Perbaiki tampilan visual laporan bulanan pada menu cetak
=> menghilangkan garis pada tampilan cetak laporan bulanan

donjo-app/views/laporan/bulanan_print.php
=> Otomatisasi Jabatan Staf Penandatangan Laporan Kependudukan Bulanan

donjo-app/views/sid/kependudukan/penduduk_form_isian.php
=> Mengubah kata KG menjadi Gram di penduduk_form_isian.php

donjo-app/models/Database_model.php, donjo-app/models/Penduduk_model.php
=> Ubah database tweb_penduduk,  kelahiran_anak_ke default menjadi NULL dan kelahiran_anak_ke menjadi kosong jika tidak diisi

donjo-app/config/routes.php
tambah fungsi sitemap generator
=> Tambah Fungsi sitemap.xml

donjo-app/controllers/Sitemap.php
=> tambah Sitemap.xml generator

donjo-app/controllers/Program_bantuan.php, donjo-app/models/Program_bantuan_model.php, donjo-app/views/program_bantuan/detail.php
solusi untuk penambahan fungsi cari pada menu bantuan
=> penambahan fungsi "cari" pada menu BANTUAN

contoh_data_awal_20190501.sql, donjo-app/models/First_artikel_m.php, donjo-app/models/Web_widget_model.php, donjo-app/views/sosmed/youtube.php, donjo-app/views/widgets/acak_artikel.php
Solusi untuk {perbaikan|fitur baru} terkait issue { #2058 , #2060 }
=> Perbaikan edit Youtube pada Widget Sosial Media dan Munculkan Widget Random Artikel

donjo-app/controllers/Keluarga.php, donjo-app/models/Pamong_model.php, donjo-app/models/Penduduk_model.php, donjo-app/models/Wilayah_model.php, donjo-app/views/home/pengurus_form.php, donjo-app/views/sid/wilayah/wilayah_form_rw.php
Solusi untuk {perbaikan} terkait issue {#2059}
=> Fix update penduduk non mandatory

donjo-app/controllers/Hom_sid.php, donjo-app/models/Header_model.php, donjo-app/views/home/desa.php
Menampilkan jumlah surat yang pernah dibuat seperti yang tercantum pada menu Arsip Layanan
Solusi untuk {fitur baru} terkait issue {#1942}
=> #1942 Tambah Fitur Cetak Surat di Dashboard > SID

assets/css/admin-style.css, donjo-app/models/Penduduk_model.php, donjo-app/views/database/kosongkan.php, donjo-app/views/export/exp.php, donjo-app/views/sid/kependudukan/penduduk.php
Solusi untuk {fitur baru} terkait issue {#1454}
=> #1454 Penambahan kolom foto pada data penduduk

donjo-app/models/Penomoran_surat_model.php
Solusi untuk {perbaikan} terkait issue {#2083}
=> #2083 Menampilkan Bulan Romawi di Penomoran Surat

donjo-app/models/Database_model.php, surat/surat_permohonan_penerbitan_buku_pas_lintas/data_rtf_surat_pengantar_permohonan_penerbitan_buku_pas_lintas.php, surat/surat_permohonan_penerbitan_buku_pas_lintas/index.html, surat/surat_permohonan_penerbitan_buku_pas_lintas/surat_pengantar_permohonan_penerbitan_buku_pas_lintas.php, surat/surat_permohonan_penerbitan_buku_pas_lintas/surat_pengantar_permohonan_penerbitan_buku_pas_lintas.rtf
Solusi untuk {fitur baru} terkait issue {#2074}
=> Surat Permohonan Penerbitan Buku Pas Lintas #2074

donjo-app/models/Database_model.php, surat/surat_ket_penghasilan_ayah/data_rtf_surat_ket_penghasilan_ayah.php, surat/surat_ket_penghasilan_ayah/index.html, surat/surat_ket_penghasilan_ayah/surat_ket_penghasilan_ayah.php, surat/surat_ket_penghasilan_ayah/surat_ket_penghasilan_ayah.rtf
Solusi untuk {fitur baru} terkait issue {#2072}
=> Surat Keterangan Penghasilan Ayah #2072

donjo-app/models/Database_model.php, surat/surat_ket_penghasilan_ibu/data_rtf_surat_ket_penghasilan_ibu.php, surat/surat_ket_penghasilan_ibu/index.html, surat/surat_ket_penghasilan_ibu/surat_ket_penghasilan_ibu.php, surat/surat_ket_penghasilan_ibu/surat_ket_penghasilan_ibu.rtf
Solusi untuk {fitur baru} terkait issue {#2073}
=> Surat Keterangan Penghasilan Ibu #2073

donjo-app/views/program_bantuan/form.php
Data Peserta Bantuan Diisi Otomatis Sesuai Data Penduduk #2101
=> Data Peserta Bantuan Diisi Otomatis Sesuai Data Penduduk #2101

donjo-app/controllers/First.php, donjo-app/controllers/Main.php, donjo-app/views/offline_mode.php
Mungkin berguna untuk menampilkan informasi pada saat situs mengalami offline mode, jadi saat situs mengalami offline mode tidak langsung redirect ke halaman admin.
seperti request di issue #2095 
Pihak desa dapat mengubah tampilan offline mode nya sendiri di file donjo-app/views/offline_mode.php
=> Add Offline Mode #2095

donjo-app/views/program_bantuan/detail.php
Solusi untuk issue #2102 - Data bantuan tidak bisa diupdate secara otomatis. Penyebab masalah ini adalah karena adanya elemen <form> dalam <form> pada line 60 dan 167. Perbaikan dengan cara submit form dialihkan ke form induk (yang paling atas).
=> Solusi untuk issue #2102

donjo-app/models/Surat_model.php
Solusi untuk {fitur baru} terkait issue {#2138}
=> Menyesuaikan Alamat Desa pada Kop Surat #2138

donjo-app/controllers/First.php, donjo-app/models/Keuangan_model.php
Penambahan Grafik RP-APBD & R-BD berdasarkan data dari database
=> Adding feature Grafik RP-APBD & R-BD

assets/js/tinymce/plugins/laporan_realisasi/plugin.min.js, donjo-app/controllers/First.php, donjo-app/models/Keuangan_model.php
perbaikan error only_full_group_by dan penambahan model grafik_pembiayaan & laporan_realisasi
=> Adding Features : grafik_pembiayaan model, laporan_realisasi model, fixing error sql_mode = only_full_group_by

assets/js/tinymce/plugins/keuangan_grafik/plugin.min.js, assets/js/tinymce/plugins/laporan_realisasi/plugin.min.js, donjo-app/controllers/First.php, donjo-app/models/Keuangan_model.php
=> adding grafik-pembiayaan desa

donjo-app/views/keuangan/widget.php, donjo-app/views/widgets/keuangan.php
Pada PR ini terdapat penambahan widget keuangan. WIdget ini bertujuan untuk menampilkan laporan keuangan secara transparan.
=> Penambahan widget keuangan

donjo-app/views/sid/kependudukan/maps.php
Solusi untuk perbaikan terkait issue #2174
=> #2174 : rubah default lokasi tempat tinggal ke config kantor desa.

donjo-app/controllers/First.php, donjo-app/models/Keuangan_model.php
untuk perapian penulisan script dan pemisahan class shortcode akan disusul
=> update table anggaran vs realisasi

donjo-app/views/widgets/keuangan.php
Berdasarkan issue #2184, saya menerapkan saran sesuai dengan saran pengguna di issue tersebut.
=> Perbaikan untuk widget keuangan

assets/js/tinymce/plugins/keuangan_grafik/plugin.min.js, assets/js/tinymce/plugins/laporan_realisasi/plugin.min.js, donjo-app/helpers/shortcode_helper.php, donjo-app/views/header.php
Solusi untuk perbaikan terkait issue #2188 , membuat condition untuk relative url dari local & server
=> [keuangan] relative url condition for local & production (published)

donjo-app/controllers/First.php, donjo-app/helpers/shortcode_helper.php, donjo-app/models/Keuangan_model.php
Solusi untuk perbaikan terkait grafik dan aturan penulisan script
=> [keuangan] fix some features and check scripting rules

donjo-app/models/Keuangan_model.php, donjo-app/views/widgets/keuangan.php
Dengan melihat issue #2192, berikut adalah perbaikan dengan melihat saran dari issues tsb.
=> Perbaikan pada widget keuangan

donjo-app/helpers/shortcode_helper.php
usul pemindahan lokasi legend oleh pak stanley ke right top corner
=> [keuangan] relocation legend position in charts

donjo-app/models/Import_model.php
Solusi untuk perbaikan terkait issue #2194
=> Perbaiki issue #2194

donjo-app/controllers/Database.php, donjo-app/models/Export_model.php, donjo-app/views/export/penduduk_excel.php
Solusi untuk perbaikan terkait issue #2193
=> Perbaiki issue #2193

donjo-app/config/routes.php, donjo-app/controllers/First.php, donjo-app/models/First_artikel_m.php, donjo-app/models/Web_artikel_model.php, themes/default/partials/content.php, themes/hadakewa/partials/content.php
Solusi untuk {perbaikan|fitur baru} terkait issue {#1911}
catatan
1. tambahkan kolom slug pada tabel artikel
2. artikel yang sudah ada di cukup diupdate untuk menambahkan isi kolom slug pada tabel artikel
=> Penambahan Slug 

donjo-app/models/Shortcode_model.php, donjo-app/views/keuangan/grafik_r_bd_chart.php, donjo-app/views/keuangan/grafik_r_pemdes_chart.php, donjo-app/views/keuangan/grafik_rp_apbd_chart.php, donjo-app/views/keuangan/tabel_laporan_rp_apbd.php
perbaikan untuk pemisahan inline script untuk grafik & tabel menjadi file baru agar bisa digunakan pada modul lain
=> [keuangan] perbaikan inline script shortcode menjadi file baru

donjo-app/models/Keuangan_grafik_model.php, donjo-app/models/Shortcode_model.php, donjo-app/views/keuangan/tabel_laporan_rp_apbd.php
Solusi untuk perbaikan aturan penulisan script
=> [keuangan] perbaikan aturan penulisan script

donjo-app/controllers/Keuangan.php, donjo-app/models/Keuangan_grafik_model.php, donjo-app/models/Keuangan_model.php
pemindahan method cek_tahun kembali ke `keuangan_model.php` untuk keperluan lainnya
=> [keuangan] pemindahan method cek_tahun dari keuangan_grafik_model

donjo-app/controllers/Keluar.php, donjo-app/controllers/Surat.php, donjo-app/models/Keluar_model.php, donjo-app/models/migrations/Migrasi_1908_ke_1909.php, donjo-app/views/surat/ajax_cetak.php, donjo-app/views/surat/keluar_print.php, donjo-app/views/surat/surat_keluar.php
Solusi untuk perbaikan  terkait issue #2151
> Catatan :
- Untuk edit keterangan di arsip layanan surat sebaiknya dibuat issue baru.
- Ketika membuat surat baru akan terjadi duplikat di arsip layanan surat, sepertinya ini bug.
=> #2151 : Perubahan ulang arsip layanan surat

donjo-app/controllers/First.php
=> [keuangan] konversi shortcode menjadi deskripsi pada kategori artikel

donjo-app/views/widgets/keuangan.php
Issue #2227 disebabkan karena script Highcharts diload 2 kali. Saya menghapus script Highcharts yang saya include sehingga Highcharts hanya diinclude sekali saja.
=> Menghapus script penyebab issue #2227

donjo-app/models/Header_model.php
Solusi untuk {perbaikan} terkait issue {#2191}
=> #2191 Merapikan Panel Statistik Dashboard Home>SID

donjo-app/views/keuangan/grafik_r_bd_chart.php, donjo-app/views/keuangan/grafik_r_pd_chart.php, donjo-app/views/keuangan/grafik_r_pemdes_chart.php, donjo-app/views/keuangan/grafik_rp_apbd_chart.php, donjo-app/views/widgets/statistik.php, themes/default/layouts/header.php, themes/default/partials/analisis.php, themes/default/partials/chart.php, themes/default/partials/high.php, themes/default/partials/statistik.php, themes/default/partials/statistik_sos.php, themes/hadakewa/layouts/header.php, themes/hadakewa/partials/analisis.php, themes/hadakewa/partials/chart.php, themes/hadakewa/partials/high.php, themes/hadakewa/partials/statistik_sos.php
solusi untuk issue #2233 
pemindahan script highchart.js ke dalam header tiap-tiap tema untuk dapat digunakan secara global, serta penghapusan load script highcharts.js pada file-file yang sudah tidak diperlukan
=> [keuangan] pemindahan load script highcharts ke dalam header.php

donjo-app/controllers/First.php, donjo-app/models/First_artikel_m.php
Solusi untuk {perbaikan|fitur baru} terkait issue {#2204}
=> slug di link artikel widget komentar

surat/surat_permohonan_perubahan_kartu_keluarga/f-1.01.php
Solusi untuk [Bug] Kesalahan Menampilkan Kodepos pada Lampiran terkait issue {#2236}
=> #2236 [Bug] Kesalahan Menampilkan Kodepos pada Lampiran

donjo-app/controllers/Keuangan.php, donjo-app/models/Keuangan_model.php, donjo-app/views/header.php, donjo-app/views/keuangan/grafik_r_bd.php, donjo-app/views/keuangan/grafik_r_pemdes.php, donjo-app/views/keuangan/grafik_rp_apbd.php, donjo-app/views/keuangan/laporan.php, donjo-app/views/keuangan/menu_laporan.php, donjo-app/views/widgets/peta_lokasi_kantor.php
perbaikan fitur grafik di halaman _keuangan > laporan_
=> [keuangan] penambahan fitur grafik di halaman keuangan > laporan

donjo-app/controllers/Keluar.php, donjo-app/models/Keluar_model.php, donjo-app/views/surat/ajax_edit_keterangan.php, donjo-app/views/surat/surat_keluar.php
Solusi untuk fitur baru terkait issue #2226
=> #2226 : Arsip layanan surat ubah isian keterangan

donjo-app/models/First_artikel_m.php, donjo-app/models/Web_artikel_model.php, donjo-app/views/web/artikel/table.php, donjo-app/views/widgets/keuangan.php
Berikut rancangan awal dari artikel statis untuk keuangan.
=> Rancangan awal artikel statis

assets/css/admin-style.css, assets/front/css/first.css, desa-contoh/css/default/desa-web.css, desa-contoh/css/hadakewa/desa-web.css, desa-contoh/css/siteman.css, donjo-app/models/Shortcode_model.php, donjo-app/views/keuangan/grafik_r_bd_chart.php, donjo-app/views/keuangan/grafik_r_pd_chart.php, donjo-app/views/keuangan/grafik_r_pemdes_chart.php, donjo-app/views/keuangan/grafik_rp_apbd_chart.php, donjo-app/views/keuangan/laporan.php, donjo-app/views/keuangan/tabel_laporan_rp_apbd.php
perbaikan pada issue #2244 dan #2245
=> [keuangan] perbaikan pada issue #2244 dan #2245

donjo-app/views/keuangan/grafik_r_bd_chart.php, donjo-app/views/keuangan/grafik_r_pd_chart.php, donjo-app/views/keuangan/grafik_r_pemdes_chart.php, donjo-app/views/keuangan/grafik_rp_apbd_chart.php
=> [keuangan] set dynamic height grafik

donjo-app/controllers/Keuangan.php, donjo-app/models/Keuangan_grafik_model.php, donjo-app/views/keuangan/grafik_r_bd_chart.php, donjo-app/views/keuangan/grafik_r_pd_chart.php, donjo-app/views/keuangan/grafik_r_pemdes_chart.php, donjo-app/views/keuangan/grafik_rp_apbd_chart.php, donjo-app/views/keuangan/laporan.php
=> [keuangan] perubahan menjadi overlapping chart

donjo-app/views/keuangan/grafik_r_bd_chart.php, donjo-app/views/keuangan/grafik_r_pd_chart.php, donjo-app/views/keuangan/grafik_r_pemdes_chart.php, donjo-app/views/keuangan/grafik_rp_apbd_chart.php
=> [keuangan] penyesuaian jarak bar dalam grafik

donjo-app/models/Keuangan_grafik_model.php, donjo-app/views/keuangan/grafik_r_bd_chart.php, donjo-app/views/keuangan/grafik_r_pd_chart.php, donjo-app/views/keuangan/grafik_r_pemdes_chart.php, donjo-app/views/keuangan/grafik_rp_apbd_chart.php, donjo-app/views/keuangan/laporan.php
=> [keuangan] perbaikan error sql_mode & perbaikan indentasi

donjo-app/controllers/Menu.php, donjo-app/views/menu/ajax_add_sub_menu_form.php, donjo-app/views/menu/form.php, donjo-app/views/widgets/keuangan.php
Di PR ini, perubahan yang saya buat adalah
- Memunculkan menu, seperti pada issue #2260
- Mengubah penulisan seperti yang disinggung pada PR #2258 
- Mengatur kembali grafik, seperti di issue #2261
=> Penyelesaian issues #2260 dan #2261

donjo-app/views/keuangan/grafik_r_bd_chart.php, donjo-app/views/keuangan/grafik_r_pd_chart.php, donjo-app/views/keuangan/grafik_r_pemdes_chart.php, donjo-app/views/keuangan/grafik_rp_apbd_chart.php, donjo-app/views/keuangan/laporan.php
=> [keuangan] perubahan nominal Rp pada tooltip grafik

donjo-app/views/keuangan/grafik_r_bd_chart.php, donjo-app/views/keuangan/grafik_r_pd_chart.php
perbaikan category yang tidak terlihat
=> [keuangan] perbaikan xAxis label category yang tidak terlihat

donjo-app/views/menu/ajax_add_sub_menu_form.php, donjo-app/views/widgets/keuangan.php
Pada PR ini, issue #2269 dan #2268 diperbaiki dan ditambah.
=> Perbaikan issues #2269 dan #2268

donjo-app/views/widgets/keuangan.php
Pada PR ini, berisi perapian kode yang tidak digunakan kembali pada widget
=> PR untuk perapian kode widget

donjo-app/views/home/ajax_kantor_desa_maps.php, donjo-app/views/sid/kependudukan/maps.php
Solusi untuk fitur baru terkait issue #2046
=> input manual kordinat kantor desa, issue #2046

donjo-app/config/routes.php, donjo-app/controllers/Feed.php, donjo-app/models/Feed_model.php, donjo-app/views/feed.php, donjo-app/views/sitemap.php
Perbaikan Tampilan Sitemap yang kurang
=> Perbaikan Tampilan Sitemap yang kurang

donjo-app/controllers/Database.php, donjo-app/models/Export_model.php, donjo-app/models/Import_model.php, donjo-app/views/export/penduduk_excel.php
Solusi untuk fitur baru terinspirasi issue #2071, untuk issue tersebut seharusnya sudah solve
=> PR Tambah "alamat_sebelumnya" di Export Database

donjo-app/models/migrations/Migrasi_1909_ke_1910.php
Solusi untuk import database yang sering bermasalah karena strict mode
=> Perbaikan Struktur Database

donjo-app/controllers/Menu.php, donjo-app/models/Laporan_penduduk_model.php, donjo-app/models/Web_dokumen_model.php, donjo-app/views/menu/ajax_add_sub_menu_form.php, donjo-app/views/menu/form.php, themes/default/layouts/header.php
Solusi untuk {perbaikan|fitur baru} terkait issue {#2319}
=> [jdih] perbaikan issue #2319

donjo-app/views/auth/index.php
=> [RBAC] Penambahan file index.php

donjo-app/controllers/Dokumen_sekretariat.php, donjo-app/models/Web_dokumen_model.php
Solusi untuk perbaikan terkait issue #2345
=> [jdih] Batasi dokumen aktif saja yang bisa tampil di web

donjo-app/views/peraturan_desa/peraturan.php
=> [jdih] #2328 membuat filter halaman jdih jadi horizontal

donjo-app/controllers/Dokumen_sekretariat.php, donjo-app/controllers/First.php, donjo-app/models/Web_dokumen_model.php, donjo-app/models/migrations/Migrasi_1910_ke_1911.php, donjo-app/views/dokumen/table.php, donjo-app/views/peraturan_desa/peraturan.php
=> [jdih] perbaikan fitur filter

donjo-app/controllers/Dokumen_sekretariat.php, donjo-app/controllers/First.php, donjo-app/models/Web_dokumen_model.php, donjo-app/views/dokumen/menu_dokumen.php, donjo-app/views/peraturan_desa/peraturan.php, themes/hadakewa/layouts/header.php, themes/hadakewa/partials/menu.tpl.php
solusi untuk issue #2353 #2355 #2357 #2358 #2359 #2360 fitur jdih
=> [jdih] Fixing issue

donjo-app/controllers/Dokumen_sekretariat.php, donjo-app/controllers/First.php, donjo-app/models/Web_dokumen_model.php, donjo-app/models/migrations/Migrasi_1910_ke_1911.php, donjo-app/views/dokumen/menu_dokumen.php, donjo-app/views/dokumen/table.php, donjo-app/views/peraturan_desa/peraturan.php
Solusi untuk #2357 #2366 #2367
=> [jdih] perbaikan bugs

themes/default/layouts/carousel.php
Solusi untuk perbaikan terkait issue #2362
=> #2362: bug fix

donjo-app/models/Keuangan_grafik_model.php, themes/hadakewa/partials/apbdesa-contoh.php, themes/hadakewa/template.php
PR ini adalah perbaikan dari 2 PR sebelumnya tentang transparansi tema di Hakadewa yang sudah diclose.
=> Integrasi transparansi tema pada tema Hakadewa

donjo-app/controllers/First.php, donjo-app/helpers/pict_helper.php, donjo-app/models/migrations/Migrasi_1910_ke_1911.php, donjo-app/views/peraturan_desa/peraturan.php, themes/default/layouts/peraturan_desa.tpl.php
perbaikan aturan penulisam script
=> [jdih] perbaikan aturan penulisam script

donjo-app/controllers/First.php, donjo-app/controllers/Penduduk.php, donjo-app/controllers/Statistik.php, donjo-app/core/MY_Controller.php, donjo-app/models/Laporan_penduduk_model.php, donjo-app/models/migrations/Migrasi_1910_ke_1911.php, donjo-app/views/statistik/laporan/side-menu.php, donjo-app/views/statistik/penduduk.php, donjo-app/views/statistik/penduduk_graph.php, donjo-app/views/statistik/penduduk_pie.php, donjo-app/views/statistik/penduduk_print.php
Solusi untuk fitur baru terkait issue #1879
=> #1879 : Statistik kependudukan bisa ditampilkan per wilayah 🚀

donjo-app/views/dokumen/form.php, donjo-app/views/dokumen/menu_dokumen.php, donjo-app/views/dokumen/table.php, themes/default/layouts/peraturan_desa.tpl.php
Sesuaikan penulisan script **HANYA** untuk JDIH
=> [jdih] rapikan script khusus untuk JDIH

donjo-app/views/peraturan_desa/peraturan.php, themes/default/layouts/header.php, themes/hadakewa/layouts/header.php
=> [jdih] fix error console

desa-contoh/config/database.php, donjo-app/models/Keuangan_grafik_model.php, themes/hadakewa/partials/apbdesa-tema.php, themes/hadakewa/template.php
Di PR ini, saya mengirimkan perbaikan atas issues di transparansi tema. Perbaikan issues adalah seperti berikut :
- Transparansi tema bisa diubah apakah mau ditampilkan atau tidak
- Transparansi tema akan mengikuti tahun terdekat dengan tahun berjalan
- Perbaikan pada tampilan transparansi tema
=> Perbaikan atas issues #2377, #2378, #2379

donjo-app/models/Keluarga_model.php, donjo-app/models/Penduduk_model.php
Solusi untuk {perbaikan|fitur baru} terkait issue {#2383.}
=> Perubahan Status Perkawinan Tidak menjadi belum

desa-contoh/css/hadakewa/desa-web.css, donjo-app/views/widgets/keuangan.php, themes/hadakewa/partials/apbdesa-tema.php
PR ini adalah solusi untuk issue #2379 dan #2397.
=> Perbaikan issue #2379 dan #2397

donjo-app/models/migrations/Migrasi_1910_ke_1911.php
Solusi untuk perbaikan terkait issue #2409
=> #2409: aktifkan submodul kategori kelompok

themes/default/layouts/carousel.php, themes/default/layouts/header.php, themes/default/layouts/slider.php, themes/hadakewa/layouts/header.php, themes/hadakewa/layouts/teks_berjalan.php
Solusi untuk perbaikan terkait issue #2401
=> Perbaiki masalah library yang tidak ikut dimuat ketika teks berjalan nonaktif

donjo-app/controllers/First.php, donjo-app/models/Keuangan_grafik_model.php, themes/hadakewa/css/first.css, themes/hadakewa/partials/apbdesa-tema.php, themes/hadakewa/template.php
Pada PR ini, terdapat solusi untuk issues #2411 dan #2412.
=> Perbaikan untuk issues #2411 dan #2412

surat/surat_permohonan_kartu_keluarga/f-1.15.php
Solusi untuk {perbaikan} terkait issue {#2446}
=> #2446 Perbaikan Lampiran Permohonan KK F-1.15

donjo-app/controllers/Keuangan.php
Perbaikan console error jika laporan keuangan belum tersedia
=> Perbaikan console error jika laporan keuangan belum tersedia

donjo-app/models/migrations/Migrasi_1910_ke_1911.php
Proses Migrasi sepertinya berjalan lancar tapi sebenarnya ada beberapa table yg tidak ikut bermigrasi karena kendala di query 
1. Query error: Incorrect integer value: '' for column 'urut' - table `setting_modul`
2. Query error: Incorrect integer value: '' for column 'level' - - table `setting_modul`
3. Query error: BLOB, TEXT, GEOMETRY or JSON column 'path' can't have a default value - table `tweb_wil_clusterdesa`
=> Perbaikan Query Migrasi

assets/css/admin-style.css
Perbaikan terkait issue #2458
Dikarenakan BS3 belum bisa menerima overflow inherit tanpa hiding scroll, maka fungsi overflow dropdown dihapus dulu sampai ada metode baru atau upgrade ke BS4
=> Perbaiki Scroll yg tidak terlihat di modul Kependudukan dll

donjo-app/models/migrations/Migrasi_1911_ke_1912.php
=> #2414: [menu analisis] nilai klaisifikasi tidak bisa lebih dari nilai 999,99

assets/js/leaflet.filelayer.js, assets/js/togeojson.js, assets/js/togpx.js, donjo-app/controllers/Gis.php, donjo-app/controllers/Statistik.php, donjo-app/models/Wilayah_model.php, donjo-app/models/migrations/Migrasi_1910_ke_1911.php, donjo-app/views/gis/maps.php, donjo-app/views/home/ajax_kantor_desa_maps.php, donjo-app/views/home/ajax_wilayah_desa_maps.php, donjo-app/views/sid/wilayah/ajax_kantor_dusun_maps.php, donjo-app/views/sid/wilayah/ajax_kantor_rt_maps.php, donjo-app/views/sid/wilayah/ajax_kantor_rw_maps.php, donjo-app/views/sid/wilayah/ajax_wilayah_dusun_maps.php, donjo-app/views/sid/wilayah/ajax_wilayah_rt_maps.php, donjo-app/views/sid/wilayah/ajax_wilayah_rw_maps.php, donjo-app/views/statistik/penduduk_graph_gis.php, donjo-app/views/statistik/penduduk_pie_gis.php
Untuk mengisi data lokasi kantor atau batas wilayah Desa/Dusun/RW/RT selain dengan Marking POI
dan Menarik garis secara manual di peta yg menuntut waktu, kesabaran dan sedikit pengetahuan ttg mapping , ada alternatif cara yg relatif lebih mudah dan bisa dilakukan semua orang dgn minimal tool yg dipakai hanya dgn HP (lebih baik tentunya dgn GPS device ssperti Garmin).
Yang diperlukan adalah aplikasi GPS Logger yg bisa merekam data 'Placemark' dan 'Trackpoint' dan menyimpan hasilnya di file GPX atau KML. Di Google Play banak pilihan, salah satunya [GPS Logger](https://play.google.com/store/apps/details?id=eu.basicairdata.graziano.gpslogger&hl=in)
1. Pastikan sudah mendapat sinyal GPS dan status GPS sudah FIX dengan melihat sudah ada posisi LATITUDE dan LONGITUDE di aplikasi.
2. Marking …
=> Import file GPX/KML ke Peta

donjo-app/controllers/Area.php, donjo-app/controllers/Garis.php, donjo-app/controllers/Plan.php, donjo-app/views/area/maps.php, donjo-app/views/area/table.php, donjo-app/views/garis/maps.php, donjo-app/views/garis/table.php, donjo-app/views/lokasi/maps.php, donjo-app/views/lokasi/table.php
Pada menu Pemetaan -> Pengaturan Peta -> Lokasi/Garis/Area; Ada fasilitas untuk memetakan Lokasi/Garis/Area yg bisa dimanfaatkan dalam konteks lebih luas misalnya memetakan Lokasi RPJM dan RPKDES.
PR ini untuk perubahan dengan ruang yg lebh besar, fungsi  impor GPX/KML dan export ke GPX.
=> Pemetaan Lokasi/Garis/Area dgn ruang yg lbh besar dan impor GPX/KML

donjo-app/controllers/Gis.php, donjo-app/models/Plan_garis_model.php, donjo-app/views/gis/maps.php
1. Centang desa/dusun/rw/rt di peta tidak konsisten #2480
2. Tidak ada pilihan untuk menampilkan garis di peta #2481
3. [Bug] Peta tidak menampilkan warna area sesuai setting tipe area #2482
4. [Bug] Fitur cari penduduk di peta tidak berfungsi baik #2484
=> Update untuk issue #2480, #2481, #2482, #2484

assets/js/leaflet-providers.js, donjo-app/views/area/maps.php, donjo-app/views/garis/maps.php, donjo-app/views/header.php, donjo-app/views/sid/wilayah/ajax_wilayah_maps.php
Update untuk issue :
1. Perubahan zoom untuk peta wilayah desa/dusun/rw/rt perlu tersimpan #2489
2. Perlu tampilkan wilayah di atas wilayah yg sedang diedit #2490
3. Perbaikan script export peta ke GPX
=> Simpan Zoom #2489 dan Tampilkan Peta wilayah di atasnya #2490

donjo-app/views/gis/content_desa.php, donjo-app/views/gis/content_dusun.php, donjo-app/views/gis/content_rt.php, donjo-app/views/gis/content_rw.php
Tersedia 2 Pilihan Type Statistik (Graph/Pie) di Peta
=> Tersedia 2 Pilihan Type Statistik (Graph/Pie) di Peta

donjo-app/views/gis/maps.php, donjo-app/views/sid/wilayah/ajax_wilayah_maps.php
Perbaikan [Bug] Wilayah dusun/rw/rt salah tampil kalau lokasi kantor tersebut belum ada #2495
=> Perbaikan #2495 dan #2496 (item : polygon tidak tampil di tengah peta)

donjo-app/views/gis/maps.php, donjo-app/views/sid/wilayah/ajax_wilayah_maps.php
Menampilkan Citra Satelite dan Opsi pilihan Basemap di Peta
1. Register di https://www.mapbox.com/ , Create Token, Copy Token
3. Copy Token ke OpenSID
Pengaturan -> Aplikasi -> Kolom 'google_key'
Untuk testing sementara bisa copy token ini :
pk.eyJ1IjoiemVwcHlzaGlkZGlxIiwiYSI6ImNrM2NjMjE1aTB1bG8zbXFoeTRlaG5oeHIifQ.hyMH01mivjhCu2SgYOx1kQ
=> Menampilkan Citra Satelite dan Opsi pilihan Basemap di Peta

donjo-app/views/gis/maps.php, donjo-app/views/sid/wilayah/ajax_wilayah_maps.php
Perbaikan Tampilan Opsi Layer Peta pada HP  issue #2509
=> Perbaikan Tampilan Opsi Layer Peta pada HP #2509

themes/hadakewa/layouts/gallery.tpl.php, themes/hadakewa/layouts/sub_gallery.tpl.php, themes/hadakewa/partials/gallery.php, themes/hadakewa/partials/sub_gallery.php
Solusi untuk perbaikan terkait issue #2528
=> Perbaiki teks berjalan tidak berfungsi normal di laman galeri dan subgaleri

donjo-app/models/Database_model.php
Pengaturan > Database > Kosongkan DB sekarang tidak menghapus data tabel ref_dokumen
Solusi untuk #2532
=> Pengaturan > Database > Kosongkan DB sekarang tidak menghapus data tabel ref_dokumen

donjo-app/controllers/First.php
Solusi untuk perbaikan terkait issue #2533
=> Widget statistik penduduk di web tidak lagi terpengaruh filter wilayah

donjo-app/views/gallery/form.php, donjo-app/views/gallery/form_sub_gallery.php
Solusi untuk perbaikan terkait issue #2529
=> #2529: Upload foto album tidak lagi wajib jika sudah ada file sebelumnya

donjo-app/views/widgets/peta_lokasi_kantor.php, donjo-app/views/widgets/peta_wilayah_desa.php, themes/default/layouts/header.php, themes/hadakewa/layouts/header.php
Tambah Opsi Pilihan Layer/Citra Satelite di Widgets Peta Lokasi/Wilayah
Note : untuk Tema DEFAULT dan HAKADEWA
=> Tambah Opsi Pilihan Layer/Citra Satelite di Widgets Peta Lokasi/Wilayah

donjo-app/views/area/maps.php, donjo-app/views/garis/maps.php, donjo-app/views/lokasi/maps.php
Tambah Opsi Pilihan Layer/Citra Satelite di Pemetaan Lokasi/Garis/Area
=> Tambah Opsi Pilihan Layer/Citra Satelite di Pemetaan Lokasi/Garis/Area

donjo-app/controllers/Keuangan.php, donjo-app/models/Keuangan_grafik_model.php
[keuangan] Perbaikan grafik Pelaksanaan & Pendapatan
=> [keuangan] Perbaikan grafik Pelaksanaan & Pendapatan

donjo-app/controllers/Keluarga.php
Solusi untuk perbaikan terkait issue #2584
=> Issue #2584 Add anggota keluarga ubah redirect tetap di daftar anggota kk

donjo-app/views/sid/wilayah/ajax_wilayah_maps.php
Solusi untuk perbaikan terkait issue #2496
=> tambah event listener buat zoom peta

donjo-app/controllers/Program_bantuan.php, donjo-app/controllers/Surat.php
Penggabungan Surat dan Lampiran pada saat ekspor dok agar tidak keMenu  Arsip Layanan Surat untuk mengunduh Lampiran
=> Penggabungan Surat dan Lampiran pada saat ekspor dok

donjo-app/controllers/First.php, donjo-app/models/First_artikel_m.php, themes/hadakewa/partials/artikel.php
Penambahan file artikel.php yang diambil dari theme default dan penambahan source untuk detail artikel kategori agenda/1000 (waktu, koordinator, tempat)
Solusi terkait issue #2597
=> #2597 Solusi Untuk Masalah Artikel Kategori Agenda

donjo-app/controllers/Web.php, donjo-app/models/Web_artikel_model.php, donjo-app/views/web/artikel/form.php, donjo-app/views/web/artikel/table.php
Solusi untuk fitur baru terkait issue #2531
=> Penambahan Menu Lihat Artikel di halaman Admin dan perubahan halaman setelah edit dan simpan artikel

donjo-app/controllers/Penduduk.php, donjo-app/views/sid/kependudukan/ajax_penduduk_maps.php, donjo-app/views/sid/kependudukan/penduduk.php
Ketika berada di lapangan untuk marking lokasi tempat tinggal penduduk, langkah proses inputnya terlalu panjang sehingga mengurangi efektivitas pekerjaan.
Langkah ini perlu dipersingkat :
Sebelum :
1.Kependudukan -> 2.Penduduk -> 3.Klik Pilih Aksi -> 4.Ubah Biodata Penduduk -> 5.Scroll ke bawah -> 6.Klik "Cari Lokasi Tempat Tinggal" -> 7.Lakukan Marking posisi -> 8.Simpan -> 9.Klik "Kembali ke Daftar Penduduk" -> 10.Ulangi Step 3-9
Sesudah :
1.Kependudukan -> 2.Penduduk -> 3.Klik Pilih Aksi -> 4.Ubah Lokasi Tempat Tinggal -> 5.Lakukan Marking posisi -> 6.Simpan -> 7.Ulangi Step 3-6
=> Persingkat Langkah Input Marking Lokasi Penduduk

donjo-app/views/sid/kependudukan/keluarga_form_a.php
Solusi untuk {perbaikan|fitur baru} terkait issue {#2632}
=> Penambahan Tombol Kembali Ke Daftar Keluarga

donjo-app/views/sid/kependudukan/ajax_penduduk_maps.php
Perbaikan ubah lokasi rumah utk yg belum ada data lokasinya
=> Perbaikan ubah lokasi rumah utk yg belum ada data lokasinya

donjo-app/views/sid/wilayah/ajax_wilayah_maps.php
Solusi untuk perbaikan terkait issue #2641
=> set value setelah create polygon

donjo-app/views/siteman.php
=> #2654 Buat checkbox untuk tampilkan password pada login ke sistem

themes/default/partials/apbdesa-tema.php, themes/default/template.php
Menampilkan Laporan Transparansi Keuangan di Tema Default
=> Menampilkan Grafik Transparansi Keuangan di Tema Default

donjo-app/models/Keuangan_grafik_model.php, donjo-app/models/Keuangan_model.php
Update proses hapus data desa -> Saat ini hapus data anggaran desa di ta_Anggaran harusnya ta_RAB
=> Update proses hapus data desa -> dari ta_Anggaran ke ta_RAB

donjo-app/models/Keuangan_grafik_model.php
Update filter di grafik pendapatan agar dapat menampilkan PAD Hasil Usaha Desa
=> Update filter di grafik pendapatan agar dapat menampilkan PAD Hasil Usaha Desa

donjo-app/models/First_artikel_m.php, donjo-app/views/widgets/arsip_artikel.php
Judul artikel menjadi Justify.
=> Merapikan tampilan Widget Artikel

donjo-app/views/setting/modul/table.php
Checkbox tdk digunakan pada menu ini
Solusi issue #2695
=> #2695 Hapus Checkbox Pada Modul dan Submodul

donjo-app/models/First_artikel_m.php, donjo-app/views/widgets/agenda.php
link menggunakan tgl+ slug
Solusi untuk issue #2692
=> #2692 Slug Pada Daftar Agenda

donjo-app/models/First_artikel_m.php, themes/default/partials/arsip.php, themes/default/partials/artikel.php, themes/hadakewa/partials/arsip.php
Solusi Yang Berkaitan Dengan Slug. Karena Adanya Penambahan Helper Untuk Slug, maka beberapa code disesuaikan.
Yang Berkaitan Dengan Slug, sbb:
1. arsip artikel belum menggunakan alamat slug #2647
2. share artikel belum menggunakan alamat slug #2646
=> Berkaitan Dengan Slug

themes/default/partials/content.php, themes/hadakewa/partials/arsip.php, themes/hadakewa/partials/content.php
=> #2704 Menggunakan Helper Slug

donjo-app/controllers/First.php, donjo-app/models/First_artikel_m.php, donjo-app/models/migrations/Migrasi_2002_ke_2003.php, themes/default/partials/artikel.php, themes/default/partials/content.php, themes/hadakewa/partials/content.php
Beberapa Kali Tercapur Dengan PR Yang Lain, Mudah2 Tidak Lagi.
Solusi untuk issue #2667
1. Membatasi Hit Pada Halaman Yang Sama Berulang Kali (Refresh);
2. Hit akan tidak akan langsung bertambah setelah masuk ke dalam detail artikel, hit akan bertambah setelah keluar dr artikel. Ini karena ada artikel dgn kategori tertentu yang menggunakan id dan slug. sehingga untuk slug harus di conversi ke id. Karena pada update hit menggunakan parameter id.
=> #2667 Artikel Telah Dibaca

donjo-app/views/sid/kependudukan/penduduk_dokumen.php
Solusi untuk {perbaikan} terkait issue {#2710}
Link pada dokumen penduduk sekarang membuka jendela baru saat di klik.
=> #2710 Dokumen Penduduk

themes/hadakewa/partials/arsip.php
Supaya dapat mengetahui jumlah pengunjung pada setiap artikel.
=> Tampilkan kolom Artikel Dibaca pada Halaman Arsip

donjo-app/helpers/donjolib_helper.php, themes/default/partials/arsip.php, themes/default/partials/artikel.php, themes/default/partials/content.php, themes/hadakewa/partials/content.php
=> Perbaikan Penulisan Hit Artikel 

themes/hadakewa/css/first.css
SUpaya huruf besar dan kecilnya hanya pada Nama Desa Saja,
Alamat dan sebagainya huruf yang menyesuaikan.
=> Menyesuaikan font pada tampilan header

excel/index.html, htaccess.txt, securimage/index.html
Solusi untuk issue #2723
Untuk saat ini sy hanya tambahkan index pd folder excel dan securimage. Krn baru itu yg sya cek dgn mengakses dgn url langsung.
=> Protec Folder

donjo-app/views/siteman.php
Solusi untuk perbaikan terkait issue {#2753}
=> #2753 bugs tampilkan kata sandi

donjo-app/views/sid/kependudukan/penduduk_log.php
Solusi untuk issue #2748
Bugs Tombol Status Dasar dan ComboBox Pada Log Penduduk
=> Perbaikan Tombol Kembalikan Status Dasar dan CheckBox

donjo-app/controllers/First.php, donjo-app/models/First_artikel_m.php
1. urutkan agenda
2. gunakan active record ci
Solusi untuk  perbaikan terkait issue  #2752
=> urutkan agenda berdasarkan tgl agenda

donjo-app/models/User_model.php, donjo-app/views/laporan/bulanan.php, donjo-app/views/laporan/bulanan_print.php, donjo-app/views/laporan/kelompok.php, donjo-app/views/laporan/kelompok_print.php
Sebelumnya pemanggilan data menggunakan result_array() pd masing2 config buatan tiap models, setelah penyesuaian config model sebagai config default yg menggunakan row_array() maka perlu perbaikan view. View tdk perlu lg menggunakan foreach untuk pemanggilan 1 baris data.
=> Penyesuaian View Stelah Menggunakan Config Model

donjo-app/views/inventaris/jalan/edit_inventaris.php, donjo-app/views/inventaris/jalan/form_tambah.php, donjo-app/views/inventaris/jalan/view_inventaris.php
Solusi untuk perbaikan issue #2628 
Sudah dirubah dari satuan KM menjadi M sesuai dengan standar ukuran jalan
=> Ubah Panjang Jalan, Irigasi dan Jaringan pada menu inventaris memakai M bukan KM

catatan_rilis_19.09-pasca.txt, donjo-app/controllers/Gallery.php, donjo-app/views/gallery/sub_gallery_table.php
Tambah tombol Up dan Down di daftar gambar album
=> Tambah tombol Up dan Down di daftar gambar album

donjo-app/models/First_artikel_m.php
Gunakan active record
Solusi perbaikan terkait issue #2785
=> #2785 Artikel yang sudah di nonaktifkan masih terindex di paging artikel

donjo-app/models/Web_artikel_model.php
Sulusi terkait issue Penerapan SLUG sedikit mengganggu #2253
=> #2253 Perubahan Judul Artikel Tidak Mempengaruhi Slug Yg Sudah Ada

donjo-app/views/web/artikel/table.php
Tombol Hapus Kategori Terhidden #2794
=> #2794 Bug Tampilan Hapus Kategori

donjo-app/models/Surat_master_model.php, donjo-app/models/Surat_model.php
Solusi untuk perbaikan terkait issue #2805 [Versi 20.03 Pasca ] : Tidak Bisa Tambah Format Surat pada pengaturan Surat
=> #2805 Perbaiki Layanan Surat

donjo-app/models/Wilayah_model.php, donjo-app/views/footer.php
Solusi untuk perbaikan terkait issue #2812
=> Perbaikan halaman Wilayah Administratif saat menambahkan data yang sama

donjo-app/controllers/Sid_core.php, donjo-app/models/Wilayah_model.php, donjo-app/views/sid/wilayah/wilayah.php, donjo-app/views/sid/wilayah/wilayah_rt.php, donjo-app/views/sid/wilayah/wilayah_rw.php
Solusi untuk perbaikan terkait issue #2815
1. Hapus checkbox dusun, rw dan rt
2. Sederhanakan function delete dusun, rw dan rt
=> #2815 Hapus checkbox dan sederhanakan function delete

donjo-app/models/First_artikel_m.php
Solusi untuk perbaikan terkait issue #2808
=> Perbaikan untuk menampilkan informasi keuangan di artikel

donjo-app/models/First_artikel_m.php, themes/hadakewa/partials/content.php, themes/klasik/partials/arsip.php, themes/klasik/partials/content.php
1. Jumlah artikel menurut kategori mengikuti pengaturan aplikasi
2. Jika jumlah tkd ada atau artikel <= dari pengaturan web_artikel_per_page maka paging dihilangkan
3. Hilangkan paging jika jumlah arsip <= 20
Solusi untuk perbaikan terkait issue #2792
=> #2792 Perbaikan Paging Artikel/Kategori/Arsip

donjo-app/models/Keluarga_model.php
Solusi untuk perbaikan terkait issue #2832
=> #2832 Perbaikan Bugs KK

donjo-app/views/analisis_master/table.php, donjo-app/views/area/table.php, donjo-app/views/garis/table.php, donjo-app/views/line/table.php, donjo-app/views/lokasi/table.php, donjo-app/views/point/table.php, donjo-app/views/sid/kependudukan/keluarga.php, donjo-app/views/sid/kependudukan/penduduk.php, donjo-app/views/sid/kependudukan/rtm.php, donjo-app/views/statistik/penduduk.php, donjo-app/views/surat/surat_keluar.php
Solusi untuk perbaikan terkait issue #2793
=> Tombol bersihkan filter

themes/hadakewa/template.php
Solusi untuk {Tampilan Header Tema Hadakewa } terkait issue {#2865}
=> Supaya judul covid tidak tertindih

donjo-app/views/man_user/manajemen_user_table.php
1. Menghilangkan ceklist untuk user default (id 1)
2. Gunakan id sebagai paramter pembanding, krn username bisa diedit.
=> Perbaikan modul pengguna 

donjo-app/controllers/First.php, donjo-app/views/web/mandiri/layanan_mandiri.php, donjo-app/views/web/mandiri/surat.php
1. Solusi untuk {Foto Penduduk Yang Login di Layanan Mandiri} terkait issue {#2866, dst.}
2. Untuk menghapus menu statis kembali ke admin utama, gimana pendapat terbanyak. :)
=> Menampilkan Foto Penduduk Yang Login di Layanan Mandiri dan Input No.Hp Hanya Angka.

donjo-app/views/feed.php
#2878 Sediakan Tanggal Posting pada RSS Feed
=> #2878 Sediakan Tanggal Posting pada RSS Feed

donjo-app/models/Mandiri_model.php
Solusi untuk perbaikan terkait issue #2874
Tidak menggunakan active record krn takutnya alur porgramnya banyak yg berubah dan menjadi bugs untuk selanjutnya.
=> #2874 PIN yg dihasilkan berada pada urutan teratas

donjo-app/models/User_model.php
1. Tambahkan akses operator pd modul baru yg ditambahkan : surat_mohon (layanan surat > daftar persyratan) dan pengunjung (admin web > pengunjung).
2. Perbaikan urutan hak_akses sesuai dgn view model yg ditampilkan di dashboard admin agar mudah dicocokkan programer lain.
3. Berikan komentar untuk hak akses pd submodul, agar mudah ditemukan programer lain.
Catatan:
Untuk selanjutnya setiap penambahan modul, tambahkan jg hak asesnya pd user operator
=> Hak akses untuk operator modul surat_mohon (layanan surat > daftar persyratan), pengunjung (admin web > pengunjung)

donjo-app/controllers/Plan.php, donjo-app/views/lokasi/form.php
1. Perbaikan kesalahan saat load data map yg di edit
2. Tambahkan warna merah pada keterangan "Kosongi jika tidak ingin merubah Foto"
Solusi untuk perbaikan terkait issue #2863 dan sudah diperbaiki sebagian melalui PR #2860
=> #2863-Perbaikan update map pada lokasi 

donjo-app/models/Program_bantuan_model.php, donjo-app/views/program_bantuan/form.php
1. Pada sasaran kk , nik digunakan sebagai id peserta
2. Lakukan penyesuaian agar tdk mengubah fungsi untuk sasaran lain.
Solusi untuk perbaikan terkait issue #2880
=> #2880 Perbaikan program bantuan untuk sasaran kk

donjo-app/views/dokumen/table.php
Solusi untuk perbaikan terkait issue #2885
=> Tampilan mobile dokumen sekretariat 

donjo-app/controllers/Program_bantuan.php, donjo-app/models/Program_bantuan_model.php, donjo-app/views/program_bantuan/edit.php
1. Jika jml peserta 0 maka sasaran dapat diganti melalui combobox pada saat mengedit program bantuan.
2. Jika  jml peserta != 0 maka sasaran tdk dapat diganti pada saat mengedit program bantuan. Combobox akan digantikal dengan label untuk menghidari inspect browser.
Solusi untuk perbaikan terkait issue #2897
Ini jg sudah bisa di riview pak @eddieridwan, @ariandii
=> Solusi alternatif terkait issue #2897

themes/klasik/partials/statistik.php
Solusi untuk perbaikan terkait issue #272
Untuk saat ini yg dihaus adalah data yg ada di tabel. Apakah data diagram jg perlu dihapus???
Mungkin bisa riview ini pak @eddieridwan , lg krja issuee yg ringan dlu
=> Hapus data jika nilainya 0 pd statistik

donjo-app/models/migrations/Migrasi_2004_ke_2005.php
Perbaikan untuk struktur tabel dgn menghapus field yg tdk digunakan/tidak diperlukan (urut)
=> Hapus field urut pd tabel artikel

donjo-app/controllers/Pengurus.php, donjo-app/models/Pamong_model.php
Solusi untuk perbaikan terkait issue #2909
=> Hindari duplikasi pemerintah desa

assets/js/anti-csrf.js
Untuk &lt;form> yang dinamis biasanya di-load by ajax
=> pasang csrf token di tag <form> dinamis; Fix CSRF Layanan Mandiri

donjo-app/controllers/Covid19.php, donjo-app/models/Covid19_model.php, donjo-app/models/User_model.php, donjo-app/views/covid19/data_pemudik.php, donjo-app/views/covid19/detil_pemudik.php, donjo-app/views/covid19/edit_pemudik.php, donjo-app/views/covid19/form_isian_pemudik.php, donjo-app/views/covid19/form_pemudik.php, donjo-app/views/covid19/konfirmasi_pemudik.php, donjo-app/views/covid19/pantau_pemudik.php, donjo-app/views/covid19/unduh-pantau.php, donjo-app/views/covid19/unduh-sheet.php
Solusi untuk fitur baru terkait issue #2923
**Fitur apa yang baru:**
1. Menambah fitur pemantauan mandiri pemudik Covid-19 dengan field (Tanggal Periksa, suhu tubuh, batuk, flu, sesak, dan keluhan lain)
**Perubahan database:**
1. Menambah tabel covid19_pantau (ada field redundan 'status_covid', untuk mempersiapkan jika dibutuhkan perubahan status; semisal dari ODP -> PDP atau PDP->Sembuh)
**Bagaimana alur penggunaan fitur ini:**
1. User memilih data H+ (dihitung dari tanggal tiba warga pemudik)
2. Muncul NIK/Warga pemudik sesuai dengan data H+ di field NIK/Warga
3. User memilih NIK/Warga pemudik (hanya warga pemudik yang berstatus wajib pantau yang muncul dalam list)
4. User memasukkan data pantauan rutin (suhu, batuh, flu, sesak, dan keluhan lain)
5. User bisa filter data pantauan …
=> #2923 Covid Monitoring (Pemantauan Pemudik) 

donjo-app/models/Covid19_model.php, donjo-app/models/migrations/Migrasi_2004_ke_2005.php
Solusi untuk perbaikan terkait issue #2948
=> #2948 add relational database

donjo-app/views/covid19/edit_pemudik.php, donjo-app/views/covid19/form_pemudik.php, donjo-app/views/covid19/pantau_pemudik.php
Solusi untuk perbaikan terkait issue #2947
**Apa saja yang divalidasi:**
_Form Pemudik_
1. NIK (required)
2. Asal pemudik (required)
3. Tanggal tiba (required, maxDate:tanggal_sekarang)
4. Status Covid-19 (required)
5. Durasi mudik (number)
_Form Pemantauan_
1. NIK (required)
2. Tanggal pemantauan (required, minData:tanggal_tiba, maxDate:tanggal_sekarang)
3. Suhu tubuh (required, number, minValue:10.0, maxValue:50.0)
**Catatan:**
1. Form validation menggunakan jquery validation
2. Mohon masukkan kembali, jika ada yang perlu divalidasi lagi.
=> #2947 form validation covid-19

donjo-app/models/Covid19_model.php
Solusi untuk perbaikan terkait issue #2949
**Field apa saja yang difilter xss:**
_Form Pemudik_
1. Asal pemudik
2. No HP
3. Email
4. Keluhan kesehatan
5. Keterangan
_Form Pemantauan_
1. Keluhan lain
2. Status covid (hidden input)
Catatan:
1. Field lain yang tidak di filter xss, sudah divalidasi oleh jquery validation
2. Mohon info lagi jika ada cara tambahan filter xss dan/atau field lainnya yang perlu difilter
=> #2949 prevent xss attack

donjo-app/controllers/Penduduk.php, donjo-app/models/Laporan_penduduk_model.php, donjo-app/models/Penduduk_model.php, donjo-app/models/migrations/Migrasi_2004_ke_2005.php, donjo-app/views/statistik/laporan/side-menu.php, donjo-app/views/statistik/penduduk.php, donjo-app/views/statistik/penduduk_gis.php, donjo-app/views/statistik/penduduk_graph.php, donjo-app/views/statistik/penduduk_pie.php, donjo-app/views/statistik/penduduk_print.php
Solusi untuk fitur baru terkait issue #2924
1. Web
Admin Web -> Menu -> Menu Statis -> Data Desa : Sub Menu -> Tambah Sub Menu -> Jenis Link : Statistik Penduduk -> Link : Status Covid
2. Admin
=> Tambahkan Data Statistik untuk Data Siaga Covid-19

donjo-app/models/Covid19_model.php
Solusi untuk perbaikan terkait issue #2953
=> #2953 Data warga yang tampil di form pemudik hanya yang berstatus hidup

donjo-app/controllers/First.php, themes/hadakewa/template.php, themes/klasik/partials/covid_local.php, themes/klasik/template.php
Selain lewat API kawalcorona, kita juga bisa menampilkan status Covid19 di wilayah desa kita dengan Local API yang datanya berasal dari input di fitur Siaga Covid19
=> Menampilkan Status Covid19 dengan Local API data

themes/klasik/partials/covid.php
Harapannya dapat mengurangi waktu pemuatan halaman karena request ke API berjalan secara asinkronus
=> Implementasi ajax untuk mengambil data kasus covid-19

assets/js/localization/messages_id.js, donjo-app/views/web/artikel/form.php
Solusi untuk perbaikan terkait issue #2864
=> #2864 Batas input judul artikel

donjo-app/helpers/donjolib_helper.php, donjo-app/views/pengunjung/print.php, donjo-app/views/pengunjung/table.php
Solusi untuk perbaikan terkait issue #2732
=> Format angka ribuan

README.md
**Membuat readme menjadi lebih bagus!**
Saya melihat readme di repository OpenSID ini kurang terbaca dan kurang menarik. Bukan menjatuhkan namun saya hanya memberi masukan. Saya sudah membuatnya mungkin lebih baik untuk dibaca . Point point penting sudah saya tebalkan menjadikannya lebih mudah membaca hal penting!
Sekian terima kasih! ❤️
> OpenSID Menurutku keren sih, gratis dan memang membantu desa desa agar lebih terdata dan termanage lebih baik! saya harap saya bisa bantu lebih di kemudia hari!
Hasil readme bisa kalian lihat di
https://github.com/Syauqizaidan/OpenSID
Terima kasih! ✨
=> Membuat readme menjadi lebih baik dan terbaca sekaligus membuatnya lebih bagus!

donjo-app/views/surat_master/table.php
Solusi untuk perbaikan terkait issue #2986
Perbaikan:
1. Penulisan
2. Modal confirm
=> #2986 Tombol hapus

donjo-app/views/keuangan/grafik_rp_apbd_chart.php, themes/hadakewa/partials/apbdesa-tema.php, themes/klasik/partials/apbdesa-tema.php
Sembunyikan Data Anggaran/Realisasi di Grafik Keuangan yang bernilai 0
=> [Keuangan] Sembunyikan Data Anggaran/Realisasi di Grafik Keuangan yang bernilai 0

assets/front/css/first.css, themes/hadakewa/partials/gallery.php, themes/hadakewa/partials/statistik_sos.php, themes/hadakewa/partials/sub_gallery.php, themes/hadakewa/partials/wilayah.php, themes/klasik/partials/gallery.php, themes/klasik/partials/statistik.php, themes/klasik/partials/statistik_sos.php, themes/klasik/partials/sub_gallery.php, themes/klasik/partials/wilayah.php
- perbaiki penulisan view dalam format php in html
- Sederhanakan script js di halaman statistik
=> refactor: perbaiki penulisan view dalam format php in html

desa-contoh/config/config.php, donjo-app/controllers/First.php, themes/hadakewa/partials/copywright.tpl.php, themes/hadakewa/template.php, themes/klasik/partials/copywright.tpl.php, themes/klasik/template.php
Menampilkan/menyembunyikan Grafik Keuangan di Footer Halaman Muka atau Semua Halaman web melalui setting di desa/config/config.php.
Terkait issue : Munculkan grafik APBDesa di semua Footer #2831
`$config['apbdes_footer'] = 1; // Tampilkan grafik APBDes di Halaman Muka Saja
$config['apbdes_footer_all'] = 0; // Tampilkan grafik APBDes di Semua Halaman`
=> [Keuangan] #2831 - Show/Hide Grafik APBDes melalui setting di desa/config/config.php

donjo-app/models/Surat_master_model.php, donjo-app/views/dokumen/dokumen_index.php, donjo-app/views/web/halaman_statis/peraturan_desa.php, donjo-app/views/widgets/arsip_artikel.php
Agar konsiten, dan tdk perlu mengubah banyak syntax jika ada perubahan struktur folder
=> #Teknis - Lokasi sumber

donjo-app/models/Web_dokumen_model.php
solusi untuk perbaikan terkait issues #3008
=> solusi untuk perbaikan terkait issues #3008

donjo-app/controllers/Mailbox_web.php, donjo-app/views/web/mandiri/header_mandiri.php
Solusi untuk perbaikan terkait issue #2875
=> Solusi untuk perbaikan terkait issue #2875

donjo-app/models/Covid19_model.php
#3002 Perbaiki Error Menu Pemantauan Covid
=> Perbaiki Error Menu Pemantauan Covid

donjo-app/views/gis/aparatur_desa_web.php
Perbaikan modal aparatur desa di peta
=> Perbaikan modal aparatur desa di peta

donjo-app/controllers/Program_bantuan.php, donjo-app/models/Program_bantuan_model.php, donjo-app/models/migrations/Migrasi_2005_ke_2006.php
Solusi untuk perbaikan terkait issue #2998
Perbaikan :
1. Hapus fild sasaran
2. Hapus 'sasaran' => $row["sasaran"]
3. Tidak perlu lg menseleksi peserta pd add_peserta agar tdk ada peserta ganda, krn pd form pendaftaran peserta sudah difilter penduduk yg sudah terdaftar/blum pd program bantuan (hanya penduduk yg tdk terdaftar sj yg ditampilkan pd select box)
=> #2998 Perbaikan program bantuan

donjo-app/views/gis/aparatur_desa_web.php, donjo-app/views/widgets/aparatur_desa.php
Memunculkan Tombol Pada Foto Aparatur Desa #3021
=> Memunculkan Tombol Pada Foto Aparatur Desa #3021

themes/hadakewa/css/first.css, themes/hadakewa/layouts/header.php
solusi terkait perbaikan #2869
=> solusi terkait perbaikan #2869

donjo-app/views/surat_keluar/form.php
1.  Sesuaikan susunan div
2. Perbaikan style textarea, select.
3. Pengaturan style untuk layar lebar, sedang dan kecil
#blum ada issunya
=> Perbaikan tampilan form tambah surat keluar

donjo-app/views/surat_masuk/form.php
1. Pengaturan style untuk layar lebar, sedang dan kecil
2. Perbaikan textarea
3. Perbaikan select yg terlalu lebar di tampilan layar kecil
4. Tambahkan penutup div yg kurang
Solusi untuk perbaikan terkait issue #1748 dan PR #2027
Jika tampilan kurang/blum ssesuai bisa tinggalkan komentar
=> #1748 Perbaikan tampilan form tambah surat masuk

donjo-app/views/widgets/statistik_pengunjung.php
1. Hanya memperbaiki cara menampilkan statistik berdasarkan panjang string jumlah pengunjung
2. Perbaikan {}
3. Masih menggunakan scrip sql lama
Solusi untuk perbaikan terkait issue #2239
Catatan : batas panjang maksmimal 7 digit (1.000.000), jika lebih akan membuat baris baru
=> #2239 Perbaikan tampilan statistik pengunjung

donjo-app/views/gis/aparatur_desa_web.php, donjo-app/views/widgets/aparatur_desa.php, donjo-app/views/widgets/galeri.php, donjo-app/views/widgets/keuangan.php, donjo-app/views/widgets/media_sosial.php, donjo-app/views/widgets/peta_lokasi_kantor.php
Seragamkan tampilan judul widget dan perbaiki caption slideup/down
=> Seragamkan tampilan judul widget dan perbaiki caption slideup/down

themes/hadakewa/css/first.css, themes/hadakewa/layouts/header.php
solusi terkait perbaikan #3031
=> solusi terkait #3031

assets/css/peta.css, assets/js/peta.js, desa-contoh/config/config.php, donjo-app/views/gis/covid_peta.php, donjo-app/views/web/halaman_statis/peta.php
Tampilan sebaran Covid-19 di Peta Web sebagai overlay yg bisa tampilkan/sembunyikan #3029
=> Tampilan sebaran Covid-19 di Peta Web sebagai overlay

donjo-app/views/web/mandiri/surat.php
1. style="width:100%; pd select2
2. responsive table
3. style textarea
4. style informasi
Solusi untuk perbaikan terkait issue #2877
=> #2877 Layanan mandiri

donjo-app/controllers/Penduduk.php, donjo-app/models/Laporan_penduduk_model.php, donjo-app/models/Penduduk_model.php, donjo-app/views/statistik/laporan/side-menu.php
Solusi sebagian untuk issue :
1. Hasilkan Data Penerima Bantuan dan Non Penerima Bantuan Secara Menyeluruh #3004
2. Tampilan Jumlah Bukan Peserta di Statistik Program Bantuan #2960
Admin :
Web :
=> Tambah Statistik Penduduk Penerima Bantuan

donjo-app/controllers/First.php
=> Beri spasi setelah "Hasil Pencarian"

donjo-app/models/migrations/Migrasi_2005_ke_2006.php, donjo-app/views/sid/kependudukan/penduduk_detail.php, donjo-app/views/sid/kependudukan/penduduk_form_isian_bersama.php
Solusi untuk { perlu ditambahkan form email di setiap kk
} terkait issue {#3025}
=>  perlu ditambahkan form email di setiap kk

donjo-app/controllers/Keluarga.php, donjo-app/controllers/Penduduk.php, donjo-app/controllers/Statistik.php, donjo-app/models/Keluarga_model.php, donjo-app/models/Laporan_penduduk_model.php, donjo-app/models/Penduduk_model.php, donjo-app/models/Statistik_keluarga_model.php, donjo-app/models/Statistik_penduduk_model.php, donjo-app/views/statistik/laporan/side-menu.php, donjo-app/views/statistik/penduduk.php, donjo-app/views/statistik/penduduk_graph.php, donjo-app/views/statistik/penduduk_pie.php
=> Tambahkan Statistik Penerima Program Bantuan Berdasarkan Sasaran

donjo-app/models/First_artikel_m.php, donjo-app/models/Web_widget_model.php, donjo-app/views/widgets/arsip_artikel.php
1. Gunakan slug #3057
2. Tambahkan artikel populer #1888
3. Perbaiki query, tampilkan yg hanya diperlukan.
Solusi untuk perbaikan terkait issue #3057, #1888
=> Perbaikan widget arsip

donjo-app/views/surat_master/surat_mohon_table.php
Hapus combobox yg tidak digunakan Layanan Surat > Daftar Persyaratan
=> #Teknis - Hapus combobox yg tidak digunakan

donjo-app/config/routes.php, donjo-app/controllers/First.php, donjo-app/controllers/Sitemap.php, donjo-app/models/Feed_model.php, donjo-app/models/First_artikel_m.php, donjo-app/models/Web_artikel_model.php, donjo-app/views/feed.php, donjo-app/views/komentar/table.php, donjo-app/views/sitemap.php, donjo-app/views/web/artikel/form.php, donjo-app/views/web/artikel/table.php, donjo-app/views/widgets/agenda.php, donjo-app/views/widgets/arsip_artikel.php, themes/hadakewa/layouts/header.php, themes/hadakewa/layouts/teks_berjalan.php, themes/hadakewa/partials/content.php, themes/klasik/layouts/header.php, themes/klasik/layouts/teks_berjalan.php, themes/klasik/partials/arsip.php, themes/klasik/partials/artikel.php, themes/klasik/partials/content.php
Solusi untuk perbaikan terkait issue #2799
Pecahan dr PR #2844
1. Ubah url dari first/artikel/$var menjadi artikel/$var #2799
=> Routing artikel seo

donjo-app/models/Program_bantuan_model.php, donjo-app/models/Statistik_penduduk_model.php
Tampilkan Program Bantuan yang Aktif saja di Statistik
=> Tampilkan Program Bantuan yang Aktif saja di Statistik

donjo-app/controllers/Penduduk.php, donjo-app/models/Penduduk_model.php
Solusi terkait issue Statistik Umur (Kategori) error 500 #3073
=> Perbaikan Link Data Statistik Umur (Kategori)

assets/js/tinymce/plugins/penerima_bantuan/plugin.min.js, donjo-app/models/Shortcode_model.php, donjo-app/views/statistik/peserta_bantuan_daftar.php, donjo-app/views/statistik/peserta_bantuan_grafik.php, donjo-app/views/web/artikel/form.php
Insert Grafik dan Tabel Penerima Bantuan sebagai Konten Artikel, 
Ada 2 pilihan yg bisa dijadikan konten artikel
1. Grafik dan Tabel Tabel Penerima Bantuan
2. Daftar Tabel Penerima Bantuan
Bisa dipilih kedua2nya sebagai sisipan artikel.
=> Insert Grafik dan Tabel Penerima Bantuan sebagai Konten Artikel

donjo-app/controllers/Statistik.php
Solusi untuk perbaikan terkait issue Bug Menu Statistik (kurang semicolon)
=> fixing semicolon in pie function statistik controller

donjo-app/views/widgets/statistik.php
Untuk data penduduk yg banyak, tampilan statistik menjadi kecil.
=> Ubah height menjadi 300px

assets/js/tinymce/plugins/penerima_bantuan/plugin.min.js
Perbaikan Menu Penerima Bantuan di TinyMCE
=> Perbaikan Menu Penerima Bantuan di TinyMCE

donjo-app/views/gis/aparatur_wilayah.php
Perbaikan tampilan foto aparatur dusun/rw/rt di PetaSID
=> Perbaikan tampilan foto aparatur dusun/rw/rt di PetaSID

donjo-app/helpers/opensid_helper.php, donjo-app/models/First_menu_m.php, donjo-app/views/menu/sub_menu_table.php, donjo-app/views/menu/table.php, themes/hadakewa/partials/menu.tpl.php, themes/klasik/partials/menu.tpl.php
Solusi untuk perbaikan terkait issue # (sy lupa issuenya dimna, tp pernah ada)
Pecahan dr PR #2844
1. Menu dgn tipe artikel (PR #3106)
2. Menu dgn tipe statistik
3. Menu lainnya
=> Menu slug artikel

donjo-app/controllers/Program_bantuan.php, donjo-app/views/program_bantuan/detail.php
Solusi untuk perbaikan|fitur baru terkait issue #3101
=> Tambah pilihan untuk menambah beberapa peserta tanpa kembali ke rincian program

donjo-app/helpers/donjolib_helper.php, donjo-app/models/Laporan_penduduk_model.php
1. Sederhanakan perhitungan presentase
2. Perbaikan cara perhitugan presentase jumlah
3. Tampilkan dan hitung data hanya untuk status_dasar 1
4. Tambah catatan penanganan fuction wilayah
5. Ubah status agar tdk terjadi nan% atau infinity%
Solusi untuk perbaikan terkait issue #3108
=> Perbaikan modul statistik

donjo-app/core/MY_Model.php, donjo-app/models/Web_menu_model.php
Pak @eddieridwan , sy cek hasil merge PR #3106 dengan perubahan. Ternyata ada yg terlewat pada menu, yg diubah hanya pada submenu sj.
=> Conver link artikel pd menu (Tertinggal)

donjo-app/controllers/First.php, donjo-app/controllers/Teks_berjalan.php, donjo-app/core/MY_Model.php, donjo-app/models/First_artikel_m.php, donjo-app/models/Teks_berjalan_model.php, donjo-app/views/web/teks_berjalan/form.php, donjo-app/views/web/teks_berjalan/table.php, themes/hadakewa/layouts/teks_berjalan.php, themes/klasik/layouts/teks_berjalan.php
Solusi untuk perbaikan terkait issue #3110 (untuk teks berjalan)
=> Perbaikan modul teks berjalan

donjo-app/controllers/First.php, donjo-app/models/Web_menu_model.php
Batasi akses fuction peraturan_desa, informasi_publik, peta, statistik, wilayah sesuai status menu
Solusi untuk perbaikan terkait issue #3114
=> #3114 Fuction dan menu aktif

donjo-app/controllers/Penduduk_log.php, donjo-app/controllers/Program_bantuan.php, donjo-app/models/Penduduk_log_model.php, donjo-app/views/global/paging.php, donjo-app/views/penduduk_log/ajax_edit.php, donjo-app/views/penduduk_log/penduduk_log.php, donjo-app/views/sid/kependudukan/penduduk_log.php
Solusi untuk perbaikan terkait issue #3121
1. Urut berdasarkan tgl_peristiwa terbaru
2. Gunakan session CI, helper selected, global/paging.php, referensi_model
3. Hapus session yg tdk digunakan
4. Sederhanakan fuction status_penduduk, sex, agama, dusun, dll menjadi 1 fuction filter dan lakuan penyesuian
5. Tambah tombol bersihkan filter
=> 3121 Log penduduk

assets/js/validasi.js, donjo-app/models/Web_dokumen_model.php
Solusi untuk perbaikan terkait issue #2937
- validasi sisi server: penerapan rule validasi **nomor_surat_keputusan** untuk field **nama** 
- validasi sisi client: penambahan rule **nomor_surat_keputusan** pada validasi.js
=> Perbaikan validasi nama dokumen pada menu admin: Sekretariat->Informasi Publik

donjo-app/config/autoload.php, donjo-app/controllers/Dpt.php, donjo-app/controllers/Sid_core.php, donjo-app/controllers/Web_widget.php, donjo-app/models/Web_menu_model.php, donjo-app/views/dpt/dpt.php, donjo-app/views/sid/wilayah/wilayah.php, donjo-app/views/web/artikel/widget.php
Penyesuaian menggunakan global/paging
=> Paging Modul

donjo-app/views/sid/kependudukan/cetak_biodata.php
Solusi untuk #3141 Tampilkan Nomor Telepon dan Email di Cetak Biodata
=> Tampilkan Nomor Telepon dan Email di Cetak Biodata

donjo-app/controllers/First.php, donjo-app/controllers/Setting.php, donjo-app/models/Setting_model.php, donjo-app/models/migrations/Migrasi_2006_ke_2007.php, donjo-app/views/setting/setting_form_web.php, themes/klasik/layouts/stat.tpl.php, themes/klasik/partials/covid.php
Saat ini Pengaturan Konfigurasi di Halaman Web melalui file desa/config/config.php dan harus diedit melalui cpanel. Seiring dengan akan bertambahnya parameter konfigurasi yg perlu diedit di file config.php ini maka dirasa perlu untuk membuat proses ini lebih mudah dan simple.
Dengan modul ini maka Pengaturan Konfigurasi di Halaman Web bisa melalui Admin Dashboard di menu Admin Web -> Konfigurasi.
=> Pengaturan Konfigurasi di Halaman Web melalui Admin Dashboard

donjo-app/controllers/Program_bantuan.php, donjo-app/models/Program_bantuan_model.php, donjo-app/views/program_bantuan/detail.php
Tambah fungsi hapus peserta terpilih di form Rincian Program Bantuan
#3146
=> Tambah fungsi hapus peserta terpilih di form Rincian Program Bantuan

donjo-app/controllers/First.php
Opsi Tampilkan APBDes di footer web memakai hasil Input manual atau Impor Data
APBDES
KONFIGURASI (Terkait PR #3119 dan #3147)
=> Opsi Tampilkan APBDes di footer web memakai hasil Input manual atau Impor Data

donjo-app/controllers/First.php, donjo-app/models/migrations/Migrasi_2006_ke_2007.php
Solusi untuk perbaikan terkait issue #3160
=> #3160 Lakukan perubahan tiap kali migrasi selain field id dan value dan perbaiki error setelah merge modul keuangan manual

assets/js/validasi.js, donjo-app/controllers/Dokumen.php, donjo-app/controllers/Dokumen_sekretariat.php, donjo-app/models/Web_dokumen_model.php, donjo-app/views/dokumen/_perdes.php, donjo-app/views/dokumen/form.php, donjo-app/views/sid/kependudukan/dokumen_form.php
Solusi parsial untuk perbaikan terkait issue #2678
=> penambahan validasi pada menu produk hukum dan informasi publik

template-surat/surat_ket_pindah_penduduk/f-1.08.php, template-surat/surat_ket_pindah_penduduk/f-1.25.php
Solusi untuk Perbaikan terkait issue {#3158}
=> tambah kolom nomor telepon untuk F-1.08 dan F-1.25

assets/js/apbdes_manual.js
Perbaikan terkait issue : seragamkan nilai Rupiah #3169
=> Tampilkan Nilai Anggaran/Realisasi dalam Format Number

donjo-app/models/Web_gallery_model.php, donjo-app/views/gallery/form.php
Solusi untuk perbaikan terkait issue #3179
=> tambahkan validasi input pada menu admin Admin Web - Galeri

donjo-app/controllers/Keluarga.php, donjo-app/models/Keluarga_model.php, donjo-app/views/sid/kependudukan/ajax_add_keluarga.php, donjo-app/views/sid/kependudukan/ajax_edit_nokk.php, donjo-app/views/sid/kependudukan/keluarga.php, donjo-app/views/sid/kependudukan/keluarga_anggota.php
Solusi untuk perbaikan terkait issue #3190
1. Pindahkah list program bantuan yg diterma KK pd halaman anggota KK
2. Tambahkan link ke program bantuan yg diterma
3. Hapus aksi menambah program bantuan lewat edit KK
=> Kk bantuan

assets/js/validasi.js, donjo-app/controllers/Siteman.php, donjo-app/controllers/User_setting.php, donjo-app/models/User_model.php, donjo-app/views/setting_pwd.php
Paksa tidak boleh gunakan password default #3055
1. Pada saat terdeteksi pengguna admin menggunakan password 'sid304', pengguna dipaksa untuk mengubah ke password lain dan tidak bisa meneruskan sebelum passwordnya diganti. 
2. Diterapkan kerumitan minimal untuk password, supaya tidak terlalu mudah ditebak -- dengan brute force sekalipun.
"Harus 6 sampai 20 characters dan sekurangnya berisi satu angka atau satu hurup uppercase atau satu hurup lowercase"
=> Password Default Harus Diganti Ketika Login

assets/js/validasi.js, donjo-app/models/User_model.php, donjo-app/views/man_user/manajemen_user_form.php, donjo-app/views/setting_pwd.php
Password Policy disesuaikan dengan US National Institute of Standards and Technology (NIST)	https://en.wikipedia.org/wiki/Password_policy#:~:text=Passwords%20must%20be%20at%20least,should%20be%20acceptable%20in%20passwords
Harus 8 sampai 20 karakter dan sekurangnya berisi satu angka dan satu huruf besar dan satu huruf kecil dan satu karakter khusus (ex .OpenSID@304)
=> Peningkatan level keamanan password sesuai Standar Password Policy

donjo-app/models/Web_kategori_model.php, donjo-app/models/Web_menu_model.php, donjo-app/views/kategori/ajax_add_sub_kategori_form.php, donjo-app/views/kategori/form.php, donjo-app/views/menu/ajax_add_sub_menu_form.php, donjo-app/views/menu/form.php
Solusi untuk perbaikan terkait issue #3178
=> Validasi pada menu Admin Web -> Menu

assets/js/validasi.js, donjo-app/helpers/opensid_helper.php, donjo-app/models/Program_bantuan_model.php, donjo-app/views/program_bantuan/create.php, donjo-app/views/program_bantuan/edit.php, donjo-app/views/program_bantuan/edit_peserta.php, donjo-app/views/program_bantuan/form.php
Solusi untuk perbaikan terkait issue #3173
=> Sempurnakan/tambahkan validasi input pada menu admin Bantuan

donjo-app/models/Web_kategori_model.php, donjo-app/models/Web_menu_model.php
Perbaikan commit #3216 -> Error ketika Tambah / Ubah Menu Statis / Dinamis
=> Perbaikan commit #3216 -> Error ketika Tambah / Ubah Menu Statis / Dinamis

donjo-app/views/gis/covid_peta.php
Penyesuaian Perubahan Config Covid ke Menu Admin Web -> Pengaturan
=> Penyesuaian Perubahan Config Covid ke Menu Admin Web -> Pengaturan

donjo-app/models/migrations/Migrasi_2006_ke_2007.php
Solusi untuk perbaikan terkait issue #3196 
1. Ambil config->kode_propinsi sebagai nilai default provinsi_covid
2. Ubah jenis provinsi_covid menjadi int (validasi untuk angka)
=> #3196 Default value provinsi_covid

.htaccess, security.md
Solusi untuk Pemblokiran backdoor php terkait issue #3223
untuk Pemblokiran Backdoor saya sudah menambahkan htaccess yang berfungsi 
untuk memaksimalkan security yang diblokir bukan hanya backdoor yang ber .php saja
namum yang ber bypass seperti .phtml , phpjpeg , ,php5 ,dan lain sebagainya
=> Perubahan Pada .htaccess untuk blokir backdoor php

assets/js/validasi.js, donjo-app/views/man_user/manajemen_user_form.php
Solusi untuk perbaikan terkait issue #3177
=> validasi input pada menu admin Pengaturan -> Pengguna

donjo-app/models/Data_persil_model.php, donjo-app/views/data_persil/create.php, donjo-app/views/data_persil/create_ext.php, donjo-app/views/data_persil/persil_jenis.php, donjo-app/views/data_persil/persil_peruntukan.php
Solusi untuk perbaikan terkait issue #3174
=> Sempurnakan/tambahkan validasi input dan penyederhanaan script pada Menu admin Pertanahan

donjo-app/views/sid/kependudukan/ajax_edit_nokk.php
Solusi untuk perbaikan terkait issue #3229
=> #3229 Bug Edit Alamat KK (Dusun, RW, RT)

donjo-app/models/Keluarga_model.php, donjo-app/views/sid/kependudukan/keluarga.php
Solusi untuk perbaikan terkait issue #3211
=> #3211 Tambah Foto KK pada daftar data KK

donjo-app/controllers/Sid_core.php, donjo-app/models/Wilayah_model.php, donjo-app/views/sid/wilayah/wilayah.php, donjo-app/views/sid/wilayah/wilayah_rt.php, donjo-app/views/sid/wilayah/wilayah_rw.php
issue #3245
1. Hapus variabel yg tdk digunakan
2. Tampilkan total rt yg tdk tampil
3. Perbaiki kesalahan menampilkan detail rt
=> #3245 Perbaikan Total Data Yang Ada Pada Wilayah RT

donjo-app/controllers/First.php, donjo-app/models/First_artikel_m.php
Solusi untuk perbaikan terkait issue #3201
=> #3201 Perbaiki Kesalahan Dalam Menampilkan Artikel

donjo-app/helpers/opensid_helper.php, donjo-app/models/Wilayah_model.php, donjo-app/views/sid/wilayah/wilayah_form.php, donjo-app/views/sid/wilayah/wilayah_form_rw.php
Solusi untuk perbaikan terkait issue #3241
=> Sempurnakan/tambahkan validasi input pada menu admin Wilayah Administratif

donjo-app/controllers/Penduduk.php, donjo-app/views/sid/kependudukan/penduduk.php, donjo-app/views/sid/kependudukan/penduduk_detail.php
Solusi untuk perbaikan terkait issue #2410
=> #2410 Bantuan penduduk pada data penduduk

donjo-app/controllers/Web.php, donjo-app/models/Web_artikel_model.php, donjo-app/views/web/artikel/table.php
Solusi untuk perbaikan terkait issue #2052
=> #2052 Artikel kategori

donjo-app/controllers/Penduduk.php, donjo-app/views/sid/kependudukan/ajax_adv_search_form.php
Solusi untuk perbaikan terkait issue  #3209
=> Sempurnakan/tambahkan validasi input pada menu admin Penduduk - Pencarian Spesifik

donjo-app/controllers/Gis.php, donjo-app/views/sid/kependudukan/ajax_adv_search_form.php
Solusi untuk perbaikan terkait issue #3208
=> Sempurnakan/tambahkan validasi input pada menu admin peta - PencarianSpesifik

donjo-app/helpers/opensid_helper.php, donjo-app/models/Plan_area_model.php, donjo-app/models/Plan_garis_model.php, donjo-app/models/Plan_line_model.php, donjo-app/models/Plan_lokasi_model.php, donjo-app/models/Plan_point_model.php, donjo-app/models/Plan_polygon_model.php, donjo-app/views/area/form.php, donjo-app/views/garis/form.php, donjo-app/views/line/ajax_add_sub_line_form.php, donjo-app/views/line/form.php, donjo-app/views/lokasi/form.php, donjo-app/views/point/ajax_add_sub_point_form.php, donjo-app/views/point/form.php, donjo-app/views/polygon/ajax_add_sub_polygon_form.php, donjo-app/views/polygon/form.php
Solusi untuk perbaikan terkait issue #3175
=> Sempurnakan/tambahkan validasi input pada menu admin Pengaturan Peta

assets/js/validasi.js, donjo-app/models/Analisis_indikator_model.php, donjo-app/models/Analisis_kategori_model.php, donjo-app/models/Analisis_klasifikasi_model.php, donjo-app/models/Analisis_master_model.php, donjo-app/models/Analisis_periode_model.php, donjo-app/views/analisis_indikator/form.php, donjo-app/views/analisis_indikator/parameter/ajax_form.php, donjo-app/views/analisis_kategori/ajax_form.php, donjo-app/views/analisis_klasifikasi/ajax_form.php, donjo-app/views/analisis_master/form.php, donjo-app/views/analisis_periode/form.php
Solusi untuk perbaikan terkait issue #3172
=> Penambahan validasi pada menu admin -> Analisis

donjo-app/controllers/Pengurus.php, donjo-app/models/Pamong_model.php, donjo-app/views/global/paging.php, donjo-app/views/home/pengurus.php
Solusi untuk perbaikan terkait issue #1063
1. Tambah dan perbaiki masalah paging
2. Gunakan builder CI
3. Set default table min-height: 350px
=> #1063 Paging 

donjo-app/controllers/Sms.php, donjo-app/models/Sms_model.php, donjo-app/views/sms/ajax_broadcast_form.php, donjo-app/views/sms/ajax_grup_form.php, donjo-app/views/sms/ajax_kontak_form.php, donjo-app/views/sms/ajax_kontak_form_edit.php, donjo-app/views/sms/ajax_sms_form.php, donjo-app/views/sms/setting.php
Solusi untuk perbaikan terkait issue #3176
=> Validasi pada menu admin SMS

donjo-app/controllers/Rtm.php, donjo-app/models/Program_bantuan_model.php, donjo-app/models/Rtm_model.php, donjo-app/models/Wilayah_model.php, donjo-app/views/global/paging.php, donjo-app/views/sid/kependudukan/kartu_rtm.php, donjo-app/views/sid/kependudukan/rtm.php, donjo-app/views/sid/kependudukan/rtm_anggota.php, donjo-app/views/sid/kependudukan/rtm_cetak.php, donjo-app/views/sid/kependudukan/rtm_unduh.php
Solusi untuk perbaikan terkait issue #3266
Point 1, sasaran RT (3) pd modul RT
Perbaikan yg dilakukan di modul RT dapat dilihat dicatatan commit.
Program bantuan yg diterma RT:
1. Link ke program_bantuan yg di terima RT
2. Link ke program_bantuan penerima (peserta)
=> #3266 Bantuan sasaran RT (3)

donjo-app/controllers/Setting.php, donjo-app/libraries/Ciqrcode.php, donjo-app/libraries/qrcode/phpqrcode.php, donjo-app/libraries/qrcode/qrbitstream.php, donjo-app/libraries/qrcode/qrconfig.php, donjo-app/libraries/qrcode/qrconst.php, donjo-app/libraries/qrcode/qrencode.php, donjo-app/libraries/qrcode/qrimage.php, donjo-app/libraries/qrcode/qrinput.php, donjo-app/libraries/qrcode/qrlib.php, donjo-app/libraries/qrcode/qrmask.php, donjo-app/libraries/qrcode/qrrscode.php, donjo-app/libraries/qrcode/qrspec.php, donjo-app/libraries/qrcode/qrsplit.php, donjo-app/libraries/qrcode/qrtools.php, donjo-app/libraries/qrcode/qrvect.php, donjo-app/models/Setting_model.php, donjo-app/models/migrations/Migrasi_2006_ke_2007.php, donjo-app/views/setting/setting_qr.php
Modul QRCOde Generator ini untuk membuat file QRCode yang nanti bisa disisipkan dalam berbagai keperluan misalnya ke dalam Artikel atau Dokumen Surat dengan konten yg bersifat umum dan tidak berisi informasi penandatanganan dokumen.
QRCode ini belum bisa dipakai untuk Tandatangan Digital kecuali PemDes sudah mendapat sertifikasinya dari BSSN dan Kemenkominfo atau pihak swasta yg sudah disertifikasi pemerintah, Jika PemDes ingin memakainya untuk TTD Digital silahkan untuk menghubungi lebih dulu badan/perusahaan untuk dapat sertifikasi dengan kisaran biaya sebesar Rp. 35,000 per 10 dokumen.
=> QRCode Generator

donjo-app/controllers/Setting.php, donjo-app/views/setting/setting_qr.php
QRCode Generator (ubah metode refresh ke ajax location.reload karena di server dengan PHP < 7.2 redirect dgn $_SERVER['HTTP_REFERER'] tidak berjalan baik)
=> QRCode Generator (ubah metode refresh ke ajax location.reload)

catatan_singkat_library_yang_digunakan.txt
Catatan penambahan library phpqrcode
=> Catatan penambahan library phpqrcode

donjo-app/controllers/Keluarga.php, donjo-app/controllers/Penduduk.php, donjo-app/views/sid/kependudukan/keluarga_anggota.php, donjo-app/views/sid/kependudukan/penduduk_detail.php
Sy sempat cek ulang commit yg pernah sy lakukan, ternyata ada kesalahan saat menampilkan data_peserta program bantuan. Yg ditampilkan adalah daftar penerima bantuan. Untuk modul RT sudah benar.
=> Patch 001 Program Bantuan Di Modul Penduduk dan KK

donjo-app/controllers/Setting.php, donjo-app/views/setting/setting_qr.php
Terjadi kesalahan saat melakukan pengosongan logo yg disimpkan setelah disimpan. Logo tetap muncul krn diambil dr data sebelumnya. Dan beberapa perbaikan dan penambahan lainnya disertakan.
Catatan: Krn menggunakan controller bersama, maka aksi pd qrcode sy buatkan dalam bentuk switch case;
=> Qrcode Perbaikan

donjo-app/controllers/Setting.php, donjo-app/views/setting/setting_qr.php
Maaf pak @eddieridwan , ada perbaikan lg. Ada perbedaan saat menampilkan data url dan directory. Sehingga terjadi kesalahan saat menampilkan data dr RFM.
Sering tertukar antara url dan directory yg digunakan.
=> Atasi permasalahan url dan directory pd qrcode

donjo-app/models/Program_bantuan_model.php, donjo-app/views/program_bantuan/form.php
Setelah dilakukan validasi, no_id_kartu pd program bantuan hanya menerima input bilangan krn menggunakan validasi bilangan(). Ada laporan dr penggun agar no_id_kartu bisa di input huruf.
Sekian
=> Perbaiki validasi no_id_kartu

donjo-app/helpers/opensid_helper.php, donjo-app/models/Database_model.php, donjo-app/models/migrations/Migrasi_2007_ke_2008.php
Fixes issues #3205 #3206
Solusi untuk perbaikan terkait issue #3205 #3206
=> Tambah tabel notifikasi

donjo-app/models/Database_model.php, donjo-app/models/Folder_desa_model.php
cara menyalin .htaccess yg pernah sy buat dan menyalin index.html kyaknya sama cuma beda paramter. Jd mungkin bisa di satukan sja.
=> Sederhanakan fuction salin_file

donjo-app/models/Wilayah_model.php
Agar tdk banyak melakukan perubah dr PR #3281, sy ganti sesuai permasalahan sja.
Di PR ini hanya memperbaiki paramter yg miss, berbeda dgn PR  sebelumnya. PR sebelumnya memperbaiki masalah : jika error, user akan berada pd form yg sama. Jd user tinggal menginput ulang.
=> error wilayah rt

donjo-app/models/Wilayah_model.php
Solusi untuk {perbaikan|fitur baru} terkait issue #3287
Kyaknya belum ada validasi di insert dan update untuk wilayah map.
=> #3287 Gunakan view penduduk_hidup dan keluarga_aktif pd modul wilayah

catatan_rilis_20.07-pasca.txt, donjo-app/views/setting/setting_qr.php
Perbaiki Modal RFM di Menu QRCode, Ganti UI ke Bhs. Indonesia dan Ukuran Mobile Responsive
#3293
Sebelum :
Sesudah :
=> Perbaiki Modal RFM di Menu QRCode, Ganti UI ke Bhs. Indonesia dan Ukuran Mobile Responsive

donjo-app/controllers/Penduduk.php
Perbaikan pada Cetak Bio Data (Script dihapus di Commit #3251)
#3296
=> Perbaikan pada Cetak Bio Data (Script dihapus di Commit 3251)

donjo-app/controllers/Database.php, donjo-app/views/database/backup.php
1. Sediakan fitur backup folder desa
2. Hapus dan sederhanakan script yg diperlukan
Untuk sementara backup folder desa disandingkan dengan backup database.
Solusi untuk {perbaikan|fitur baru} terkait issue #3301
Catatan/saran :
- Perlu lakukan penyesuaian ulang isi dari modul database, krn dr view saling terpencar dan format pemanggilan viewnya berbeda dgn modul lainnya.
- Untuk restore folder desa buatkan issue terisah (kalau merasa perlu). Adapun untuk restore folder desa yakni harus memasukkan password login.
=> backup folder desa

donjo-app/core/MY_Controller.php, donjo-app/models/Notif_model.php, donjo-app/views/notif/pengumuman.php
Solusi untuk perbaikan terkait issue #3205 
Catatan: ajax sudah ditambahkan di kedua tombol. Jika setuju, maka update tabel notifikasi. Jika tidak setuju, sistem akan _logout_ pengguna.
=> Tambah ajax di tombol pengumuman

assets/js/peta.js, donjo-app/controllers/Area.php, donjo-app/controllers/Garis.php, donjo-app/controllers/Plan.php, donjo-app/views/area/maps.php, donjo-app/views/garis/maps.php, donjo-app/views/header.php, donjo-app/views/lokasi/maps.php
#3319
Tampilkan Layer Infrastruktur Desa di Pemetaan Area/Garis/Lokasi
=> Tampilkan Layer Infrastruktur Desa di Pemetaan Area/Garis/Lokasi

.gitignore, catatan_singkat_library_yang_digunakan.txt, donjo-app/controllers/Hom_sid.php, donjo-app/helpers/opensid_helper.php, donjo-app/libraries/Curly.php, donjo-app/libraries/Release.php, donjo-app/views/home/desa.php
Pakai branch yang ini saja @afa28, branch yang lama (#3307) terhapus.
=> #3202 Notifikasi update

donjo-app/controllers/Menu.php, donjo-app/models/Web_menu_model.php
Solusi untuk perbaikan terkait issue #3351
Catatan : saat ini validasi insert dan update dilakukan scr terpisah. Mungkin bisa dibuatkan fuction validasi yg bisa digunakan untuk insert maupun update.
=> #3351 External link

donjo-app/models/User_model.php
#3329 Hak akses Operator di Keuangan Manual
=> #3329 Hak akses Operator di Keuangan Manual

assets/js/tinymce/plugins/laporan_keuangan/plugin.min.js, donjo-app/models/Shortcode_model.php, donjo-app/views/keuangan/tabel_laporan_rp_apbd_artikel.php
#3341 Tambah Pilihan Laporan Keuangan Per Semester di Artikel
=> #3341 Tambah Pilihan Laporan Keuangan Per Semester di Artikel

assets/js/peta.js, donjo-app/controllers/First.php, donjo-app/models/Plan_area_model.php, donjo-app/models/Plan_garis_model.php, donjo-app/models/Plan_line_model.php, donjo-app/models/Plan_lokasi_model.php, donjo-app/views/widgets/peta_lokasi_kantor.php, donjo-app/views/widgets/peta_wilayah_desa.php
Aktifkan fungsi tampilkan/sembunyikan peta infrastruktur di peta website
#3328
=> Aktifkan fungsi tampilkan/sembunyikan peta infrastruktur di peta website

donjo-app/views/database/migrasi_cri.php
Agar modal tdk tertutup saat melakukan migrasi
=> Agar modal tdk tertutup saat melakukan migrasi

donjo-app/models/Shortcode_model.php
Perbaiki link view grafik penerima bantuan di sisipan artikel :
Sebelumnya : `include("donjo-app/views/statistik/penduduk_grafik.php");`
Seharusnya : `include("donjo-app/views/statistik/penduduk_grafik_web.php");`
=> Perbaiki link view grafik penerima bantuan di sisipan artikel

donjo-app/core/MY_Controller.php
Solusi untuk perbaikan terkait issue #3370
=> #3370 Set default tema klasik

assets/js/peta.js
MarkerCluster sekarang dapat ditampilkan di Layer Mapbox
=> MarkerCluster sekarang dapat ditampilkan di Layer Mapbox

donjo-app/models/Laporan_penduduk_model.php, donjo-app/models/Statistik_penduduk_model.php, donjo-app/views/statistik/penduduk.php
Solusi untuk perbaikan terkait issue #3348
=> Ubah cara hitung jumlah penerima bantuan keluarga

donjo-app/models/Plan_area_model.php, donjo-app/models/Plan_garis_model.php, donjo-app/models/Plan_line_model.php, donjo-app/models/Plan_lokasi_model.php, donjo-app/models/Plan_point_model.php, donjo-app/models/Plan_polygon_model.php
Sebelumnya peta area/garis/point yang sudah dibuat hanya akan ditampilkan sampai maximum 500 record saja. Dengan perkembangan jumlah record yg semakin banyak dientri oleh pengguna maka perlu dinaikan limitnya menjadi 1000 record supaya semua record peta bisa ditampilan.
=> Menaikan limit view record di peta area/garis/point dari 500 ke 1000 record

assets/js/peta.js
Tampilkan default layer ketika pilih layer mapbox tetapi tidak ada access token
=> Tampilkan default layer ketika pilih layer mapbox tetapi tidak ada access token

donjo-app/controllers/Rtm.php, donjo-app/models/Rtm_model.php, donjo-app/views/sid/kependudukan/ajax_add_rtm.php, donjo-app/views/sid/kependudukan/rtm.php
Solusi untuk perbaikan terkait issue #3361
Setelah melakukan penambahan data baru, pengurutan diambil berdasarkan tgl_daftar paling baru.
=> Pengurutan RT

donjo-app/controllers/Statistik.php, donjo-app/controllers/Statistik_web.php
Maaf pak @eddieridwan , ini ada kesalahan. Nilainya tdk tersimpan di $data. Jd yg sy perbaiki malah masih bermasalah, sebelum PR  #3391 di merge masih normal. Tp pas sudah di merge $data tdk tersipan, ini krn ada penyesuaian dengan modul GIS yg menggunakan controller statsitik jg.
Untuk issue #3384
=> Simpan value pd variable $data

donjo-app/models/Header_model.php
Solusi untuk {perbaikan} terkait issue {#3409}
=> #3409 Perbaiki salah masuk menu Program Bantuan

donjo-app/models/First_artikel_m.php, themes/hadakewa/layouts/slider.php, themes/klasik/layouts/slider.php
Solusi untuk {perbaikan|fitur baru} terkait issue #3187, #3110
=> #3187, #3110 Slug pd slider

donjo-app/controllers/Keluarga.php, donjo-app/views/sid/kependudukan/keluarga_anggota.php
Solusi untuk perbaikan terkait issue #2976
=> #2976 Hapus tombol "Hapus Data Terpilih" Anggota KK

donjo-app/models/Database_model.php, donjo-app/models/migrations/Migrasi_2008_ke_2009.php, donjo-app/views/nav.php
1. Gunakan helper jecho
2. Hapus url parrent menu Layanan Mandiri
Solusi untuk perbaikan terkait issue #3354
=> #3354 Penyesuaian navigasi, dan akses modul operator

donjo-app/models/First_artikel_m.php, themes/hadakewa/layouts/slider.php, themes/klasik/layouts/slider.php
Issue #3110
Untuk case 2, silahkan buat issuenya
=> Slider case 1, 2

donjo-app/controllers/Gis.php, donjo-app/controllers/Menu.php, donjo-app/controllers/Statistik.php, donjo-app/models/Laporan_penduduk_model.php, donjo-app/models/Program_bantuan_model.php, donjo-app/models/Referensi_model.php, donjo-app/views/menu/ajax_add_sub_menu_form.php, donjo-app/views/menu/form.php, donjo-app/views/statistik/rentang_umur.php, donjo-app/views/statistik/side_menu.php
Solusi untukperbaikan terkait issue #3414
1. Gunakan referensi_model.php sebagai referensi utama
2. Hapus referensi yg fungsinya sama
3. Lakukan penyesuaian pd modul yg mengalami dampak dr perubahan
4. Perbaikan side menu untuk kategori rentang umur
5. License
=> #3414 Referensi

donjo-app/models/Kelompok_model.php, donjo-app/views/kelompok/anggota/form.php, donjo-app/views/kelompok/form.php
Solusi untuk perbaikan terkait issue #3424 
saya merubah query mysql pada function list_penduduk untuk menghasilkan alamat lengkap pada kolom pencaerian form ketua kelompok dan for anggota kelompok.
=> Pencarian Nama untuk ketua kelompok dan anggota

donjo-app/views/kelompok/anggota/form.php, donjo-app/views/kelompok/form.php
=> Perbaikan PR #3427

donjo-app/controllers/Penduduk.php, donjo-app/helpers/opensid_helper.php, donjo-app/models/Laporan_penduduk_model.php, donjo-app/models/Penduduk_model.php, donjo-app/models/Referensi_model.php, donjo-app/models/migrations/Migrasi_2008_ke_2009.php
Solusi untuk perbaikan dan fitur baru terkait issue #885, issue kesalahan perhitungn statistik penduduk lainnya (entah dmna issuenya).
1. Perbaiki perhitungan statistik penduduk untuk (belum mengisi, total) kecuali kepemilikan KTP (krn perhitungannya beda sendiri dan jg sdah ada issuenya)
2. Tambahkan agar jumlah dapat menampilkan link referensi.
3. Sederhanakan fuction referensi untuk filter
=> #885 Perbaikan perhitungan dan link statistik penduduk

donjo-app/models/migrations/Migrasi_2008_ke_2009.php
Perbaikan dari perubahan alur link pd modul web > artikel, dimana sebelumnya menggunakan `web/index/100` menjadi `web/tab/100`
=> Penyesuaian link agenda pd widget agenda

donjo-app/views/identitas_desa/form.php
Solusi untuk {perbaikan} terkait issue {#3447}
=> Perbaiki Kolom Kecamatan di Identitas Desa #3447

donjo-app/views/inventaris/tanah/form_tambah.php
Solusi untuk perbaikan Penambahan Item pilihan pada isian data inventaris terkait issue {#3451}
=> #3451 Penambahan Item pilihan pada isian data inventaris

donjo-app/controllers/Statistik.php
=> Perbaikan bug tampilan side menu untuk kategori statistik umur (rentang)

donjo-app/controllers/Penduduk.php, donjo-app/models/Laporan_penduduk_model.php, donjo-app/models/Penduduk_model.php, donjo-app/models/Referensi_model.php
Solusi untuk {perbaikan|fitur baru} terkait issue #743
=> #743 Statistik hubungan dalam KK

donjo-app/views/web/artikel/form.php, themes/hadakewa/layouts/header.php, themes/klasik/layouts/header.php, themes/klasik/partials/artikel.php
Solusi untuk perbaikan terkait issue #3467
Catatan:
- Perbaikan ada di file tema, jadi untuk desa yang memakai tema lain barangkali harus disesuaikan
- Saya tambahkan juga perbaikan di sisi admin, sehingga ketika edit artikel yang judulnya ada tanda petik tidak terpotong
=> Perbaikan tag meta title dan form input title untuk keperluan sharing di socmed

donjo-app/views/program_bantuan/cetak.php
Solusi untuk perbaikan program_bantuan fitur cetak dan unduh terkait issue #3479
=> menyesuaikan kolom cetak dengan kolom fitur detail program bantuan

donjo-app/controllers/First.php, donjo-app/views/web/mandiri/header_mandiri.php, donjo-app/views/web/mandiri/mandiri.php
Solusi untuk {perbaikan|fitur baru} terkait issue #2866 #2945
=> #2866 #2945 Hapus menu, hapus login, buat table reponsive

donjo-app/controllers/Penduduk.php, donjo-app/models/Penduduk_model.php
Solusi untuk perbaikan terkait issue #3492
=> Perbaikan fitur pencarian spesifik penduduk

donjo-app/controllers/Suplemen.php, donjo-app/views/suplemen/form.php, donjo-app/views/suplemen/suplemen.php
Solusi untuk {perbaikan|fitur baru} terkait issue #3504
=> #3504 Filter Sasaran Modul Suplemen

donjo-app/models/Suplemen_model.php, donjo-app/views/suplemen/form.php
Solusi untuk {perbaikan|fitur baru} terkait issue #3506
=> #3506 Form Suplemen

donjo-app/controllers/Mandiri_web.php
Solusi untuk {perbaikan|fitur baru} terkait issue #3508
=> Bug Lanyan Mandiri

donjo-app/controllers/Dokumen.php, donjo-app/helpers/opensid_helper.php, donjo-app/models/Database_model.php, donjo-app/models/migrations/Migrasi_2009_ke_2010.php, donjo-app/views/dokumen/form.php
Solusi untuk {perbaikan|fitur baru} terkait issue #3514
=> #3514 Nama Dokumen, Maxlength="100"

donjo-app/views/suplemen/suplemen.php
Solusi untuk {perbaikan|fitur baru} terkait issue  #3522
=> #3522 Disabled hapus data terdata = 0

donjo-app/controllers/Program_bantuan.php, donjo-app/views/program_bantuan/detail.php
Solusi untuk {perbaikan|fitur baru} terkait issue #3523
1. Pisahkan form cari dan paging
2. Sinkronkan selec page dan paging (hapus fuctin detail_clear(); yg menggangu paging halaman)
=> #3523 Selec Page Program bantuan

donjo-app/controllers/Penduduk.php, donjo-app/views/sid/kependudukan/penduduk_form_isian_bersama.php
Solusi untuk perbaikan terkait issue #3532
Perubahan untuk kondisi Tidak Aktif menjadi Tidak Tetap
=> Fix: Status Kependudukan issue #3532

donjo-app/models/Surat_model.php
Solusi untuk perbaikan terkait issue #3503
=> perbaikan cetak surat penghasilan orangtua

donjo-app/controllers/Keluarga.php, donjo-app/models/Keluarga_model.php, donjo-app/models/Referensi_model.php
Solusi untuk perbaikan terkait issue #3527
Anggota KK harus penduduk tetap
=> Fix: Anggota KK harus penduduk tetap #3527

donjo-app/models/Penduduk_log_model.php, donjo-app/views/penduduk_log/penduduk_log.php
Solusi untuk perbaikan terkait issue #3519
=> Tambah foto pada menu log penduduk

donjo-app/controllers/Keluarga.php, donjo-app/controllers/Penduduk.php, donjo-app/models/Keluarga_model.php, donjo-app/models/Penduduk_model.php, donjo-app/views/sid/kependudukan/ajax_search_kumpulan_kk.php, donjo-app/views/sid/kependudukan/ajax_search_kumpulan_nik.php, donjo-app/views/sid/kependudukan/keluarga.php, donjo-app/views/sid/kependudukan/penduduk.php
Solusi untuk fitur baru terkait issue #3422
Maksimal 20 Nomor NIK / KK
Setiap NIK / KK dipisahkan dengan tanda koma (,)
contoh 5201142005716996,5201140706966997,5201140705156994
Apabila NIK / KK tidak terdiri dari 16 digit, apabila salah satu NIK / KK tidak tediri dari 16 digit, maka NIK / KK tersebut tidak masuk dalam pencarian
contoh : 5201142005716996,520114070,5201140705156994
maka yang dicari hanya NIK / KK pada urutan pertama dan terakhir
=> Menambahkan fitur pencarian NIK/KK lebih dari satu NIK/KK

donjo-app/controllers/Siteman.php, donjo-app/views/header.php
Solusi untuk perbaikan terkait issue #3552 dan #2942
=> perbaikan untuk by pass url siteman/auth dan login kembali bisa max 3 kali

donjo-app/controllers/Data_persil.php, donjo-app/models/Data_persil_model.php, donjo-app/views/data_persil/persil.php, donjo-app/views/data_persil/persil_excel.php, donjo-app/views/data_persil/persil_print.php
Solusi untuk perbaikan terkait issue #3543
=> fix masalah unduh, cetak data persil

donjo-app/controllers/Cdesa.php
Solusi untuk perbaikan terkait issue #3549
=> lepas control nama pemilik cdesa harus unik

donjo-app/models/Surat_model.php
Solusi untuk perbaikan terkait issue #3558
=> perbaikan Surat_model.php terkait issue #3558

donjo-app/controllers/Analisis_statistik_jawaban.php, donjo-app/controllers/Cdesa.php, donjo-app/controllers/Keluar.php, donjo-app/core/MY_Controller.php
Setelah saya cek kembali ada beberapa controller  memanggil view header. Untuk menu analisis_statistik_jawaban/form terjadi error karena file views/analisis_statistik_jawaban/form.php memang tidak ada
=> perbaikan penyederhanaan controller

donjo-app/controllers/Web.php, donjo-app/models/Web_artikel_model.php, donjo-app/views/web/artikel/form.php, donjo-app/views/web/artikel/table.php
1. Perbaiki url modul admin web > artikel
2. Sederhanakan komentar_lock dan artikel_lock
3. Gunakan session , query bulider CI3
4. Gunakan style table yg sama
Penyesuaian ulang untuk perubahan pd PR #3252
=> Perbaiki url modul web > artikel

donjo-app/controllers/Area.php, donjo-app/controllers/Garis.php, donjo-app/controllers/Line.php, donjo-app/controllers/Plan.php, donjo-app/controllers/Point.php, donjo-app/controllers/Polygon.php, donjo-app/core/MY_Controller.php
Solusi untuk perbaikan terkait issue #3575
=> perbaikan expand menu

assets/css/admin-style.css, donjo-app/views/header.php, donjo-app/views/web/mandiri/layanan.php
Perbaikan tampilan notifikasi, table responsive dan hapus internal css layanan mandiri
=> Notifikasi

donjo-app/models/Surat_masuk_model.php, donjo-app/views/surat_masuk/form.php
Solusi untuk {perbaikan|fitur baru} terkait issue #3594
1. Tambah required pd Kode/Klasifikasi Surat
2. Tambah kondisi insert_disposisi_surat_masuk jika jabatan kosong (Tdk ada disposisi yg terpilih)
3. Hapus div yg berlebihan, tambah tag penutup div yg kurang
=> #3594 Error simpan surat masuk

assets/css/admin-style.css, donjo-app/models/Database_model.php, donjo-app/models/migrations/Migrasi_2009_ke_2010.php, donjo-app/models/migrations/Migrasi_2010_ke_2011.php, donjo-app/views/analisis_indikator/parameter/ajax_form.php, donjo-app/views/global/validasi_form.php
Solusi untuk {perbaikan|fitur baru} terkait issue #3596
**PERBAIKAN :**
1. margin-bottom dari 5px jd 10px pd form-group untuk layar kecil.
2. tipe data field nilai dr TINYINT jd INT.
3. input number min=0, max=999.
4. global/validasi_form.php
=> #3596 max input nilai 999

donjo-app/controllers/Analisis_statistik_jawaban.php, donjo-app/views/analisis_statistik_jawaban/table.php
Solusi untuk {perbaikan|fitur baru} terkait issue #3577
1. Hapus fuction yg tdk digunakan
-  parameter() -> yg digunakan adalah subjek_parameter yg isinya hampir sama.
-  form();
-  insert();
-  update();
2. Gunakan paging/global
3. Gunakan selected();
4. Gunakan style table yg sdah ada.
=>  #3577 Hapus fuction yg tdk digunakan

donjo-app/models/Surat_model.php
Solusi untuk {perbaikan|fitur baru} terkait issue #3617
=> #3617 set_ucwords dusun untuk template surat

donjo-app/helpers/opensid_helper.php, donjo-app/models/migrations/Migrasi_2010_ke_2011.php
Solusi untuk {perbaikan|fitur baru} terkait issue #3619
=> #3619 Perbaiki struktur table `analisis_parameter`

donjo-app/helpers/opensid_helper.php, donjo-app/models/Analisis_respon_model.php, donjo-app/views/analisis_respon/table.php
Yang perlu menggunakan penduduk_hidup dan keluarga_aktif hanya di modul analisis respon. Sedangkan modul analisis analisis_laporan dan analisis analisis_statistik_jawaban tdk perlu diterapkan krn kedua modul ini menyimpan hasil analisis baik yg sdah dilakukan sejak lama (yg bisa sj penduduktsb sdah meninggal/pindah).
1. Guanakan penduduk_hidup u/ analisis_respon
2. Guanakan keluarga_aktif u/ analisis_respon
3. Gunakan helper seclected()
4. Tambahkan info jika data tdk tersedia
5. Gunakan style table yg seragam
Solusi untuk {perbaikan|fitur baru} terkait issue #2629
=> Gunakan penduduk_hidup dan keluarga_aktif pd modul analisis > analisis respon

donjo-app/controllers/First.php, donjo-app/models/Referensi_model.php, themes/hadakewa/layouts/analisis.tpl.php, themes/hadakewa/partials/analisis.php, themes/klasik/layouts/analisis.tpl.php, themes/klasik/partials/analisis.php
Solusi untuk perbaikan terkait issue #3624
=> Batasi akses menu web untuk data_analisis

donjo-app/controllers/Suplemen.php, donjo-app/models/Suplemen_model.php, donjo-app/views/global/ttd_pamong.php, donjo-app/views/suplemen/cetak.php, donjo-app/views/suplemen/edit_terdata.php, donjo-app/views/suplemen/form_terdata.php, donjo-app/views/suplemen/suplemen.php, donjo-app/views/suplemen/suplemen_anggota.php
Solusi untuk {perbaikan|fitur baru} terkait issue #3609 #3608
1. Tambahkan info no. kk untuk sasaran penduduk pd table, cetak dan unduh
2. Tambahkan info nik kk untuk sasaran keluarga pd table, cetak dan unduh
3. Gunakan helper sql_in_list()
4. Perbaiki url tombol kembali pd form terdata
5. Tambahkan informasi jika data pd table tdk ada/belum tersedia
6. Gunakan Active Record CI
=> #3609 #3608 Tambahkan no. kk u/ sasaran penduduk dan nik u/ sasaran keluarga

donjo-app/controllers/Keluarga.php, donjo-app/models/Keluarga_model.php, donjo-app/models/Laporan_penduduk_model.php, donjo-app/views/statistik/penduduk.php
1. Gunakan keluarga_aktif.
2. Sesuaikan detail statistik u/ JUMLAH dan TOTAL.
3. Tambahkan  target="_blank".
4. Gunakan style table yg sdah ada.
Solusi untuk {perbaikan|fitur baru} terkait issue #3641
=> #3641 Sesuaikan ulang statistik keluarga > kelas_sosial

donjo-app/controllers/First.php, donjo-app/models/First_artikel_m.php
Solusi untuk perbaikan #3200 
Menurut analisa saya, function hit() di first_artikel_m yang sebelumnya dipanggil di function get_artikel() harus dipindah keluar. Karena function get_artikel ini juga di panggil dalam function menu_slug milik MY_Model sehingga akan dipanggil berulang kali.
Solusinya memindahkan proses update hit ke controller pemanggil yaitu function artikel() pada controllers First
=> memindahkan pemanggilan hit ke controller

themes/klasik/partials/artikel.php
Solusi untuk {perbaikan|} terkait issue {#3649}
=> fix bug buka / tutup komentar artikel #3649

donjo-app/controllers/Suplemen.php, donjo-app/models/Suplemen_model.php, donjo-app/views/suplemen/suplemen.php, donjo-app/views/suplemen/suplemen_anggota.php
Solusi untuk fitur baru terkait issue #3511 
penambahan fitur cari pada rincian data suplemen
=> penambahan fitur pencarian issue#3511

donjo-app/models/Suplemen_model.php
Solusi untuk {perbaikan|} terkait issue#3610
=> fix: tampilkan alamat lengkap sasaran keluarga issue#3610

assets/css/admin-style.css, donjo-app/controllers/Rtm.php, donjo-app/views/sid/kependudukan/rtm.php, donjo-app/views/sid/kependudukan/rtm_anggota.php
1. Hapus method cetak_statistik($tipe = 0) yg tk digunakan
2. Gunakan style table yg sdah ada
3. Hapus internal css dan gunakan external css
4. Tambahkan info jika data tdk tersedia
Solusi untuk {perbaikan|fitur baru} terkait issue #1680
=> #1680 Modul RTM

donjo-app/views/sid/kependudukan/rtm.php, donjo-app/views/sid/kependudukan/rtm_anggota.php
Kembalikan <section class="content" id="maincontent"> agar pesan success/error muncul.
Susulan Commit #https://github.com/OpenSID/OpenSID/commit/43926d146e40509373b29c9d52bbbed061c4cd37
=> Susulan Commit #43926d1

assets/css/admin-style.css, donjo-app/views/global/paging.php
1. Jika $func = 'index' atau page = 1 maka set site_url("$this->controller")
2. Ubah pembagian size menjadi col-3 dan col-9
3. Hapus script yg tdk digunakan
Solusi untuk {perbaikan|fitur baru} terkait issue #1762
=> style paging

donjo-app/models/Analisis_laporan_model.php
1. Menampilkan laporan pada kondisi nilai = minimal indikator
2. Perubahan menggunakan session CI3
Solusi untuk perbaikan terkait issue #3683
=> Perbaikan pada Laporan Hasil Klasifikasi

donjo-app/controllers/Dpt.php, donjo-app/controllers/Keluarga.php, donjo-app/controllers/Penduduk.php, donjo-app/controllers/Penduduk_log.php, donjo-app/controllers/Rtm.php, donjo-app/models/Dpt_model.php, donjo-app/models/Keluarga_model.php, donjo-app/models/Penduduk_log_model.php, donjo-app/models/Penduduk_model.php, donjo-app/models/Rtm_model.php
PERBIAKAN:
1. Ubah limit default pd model dari 500 menjadi 30000
Solusi untuk {perbaikan|fitur baru} terkait issue #3670
=> Limit Cetak/Unduh Data

donjo-app/controllers/Penduduk.php, donjo-app/views/sid/kependudukan/penduduk.php
1. Perbaiki link ke modul RTM
2. Gunakan helper url_order()
3. Konsisten gunakan style table yg sama,  hapus css internal
4. Gunakan global/filter_wilayah dan penyesuain dgn fuction dusun, rw, rt menjadi filter
5. Tambahkan keterangan tittle/petunjuk pencarian
Solusi untuk {perbaikan|fitur baru} terkait issue #3694
=> Susulan PR : Perbaikan Link Ke Modul RTM

donjo-app/views/sid/kependudukan/rtm_cetak.php
1. Hanya memperbaiki no urut rtm yg tdk tampil pd saat di cetak
TODO : Gunakan format cetak yg sudah disediakan
Solusi untuk {perbaikan|fitur baru} terkait issue #3685
=> Susulan PR : Perbaikan No. Urut Cetak RTM

donjo-app/controllers/Statistik.php, donjo-app/views/global/format_cetak.php, donjo-app/views/statistik/penduduk.php, donjo-app/views/statistik/penduduk_cetak.php
Seragamkan format pamong_ttd laporan
Solusi untuk perbaikan terkait issue #3693
=> Perbaikan Sebutan Jabatan Kepala Desa Pada Laporan Statisik

donjo-app/controllers/Kelompok.php, donjo-app/views/kelompok/table.php
Solusi untuk {perbaikan} terkait issue #3702
=> Perbaiki tombol Ubah Data Kelompok

donjo-app/models/Laporan_penduduk_model.php, donjo-app/models/Statistik_penduduk_model.php, donjo-app/views/statistik/penduduk.php
Solusi untuk perbaikan terkait issue #3653
=> Perbaikan perbedaan Jumlah Penerima antara Menu Admin dan Website Desa

donjo-app/controllers/Web.php
Solusi untuk perbaikan terkait issue #3712
=> fix: perbaiki form tambah artikel untuk kontributor

catatan_rilis_20.11.txt, contoh_data_awal_20201101.sql, desa-contoh/upload/.htaccess, desa-contoh/upload/artikel/.htaccess, desa-contoh/upload/dokumen/.htaccess, desa-contoh/upload/galeri/.htaccess, desa-contoh/upload/gis/.htaccess, desa-contoh/upload/gis/area/.htaccess, desa-contoh/upload/gis/garis/.htaccess, desa-contoh/upload/gis/lokasi/.htaccess, desa-contoh/upload/gis/lokasi/point/.htaccess, desa-contoh/upload/gis/lokasi/point/index.html, desa-contoh/upload/pengesahan/.htaccess, desa-contoh/upload/thumbs/.htaccess, desa-contoh/upload/user_pict/.htaccess, desa-contoh/upload/widgets/.htaccess, donjo-app/helpers/opensid_helper.php, donjo-app/models/Database_model.php
1. Ubah versi aplikasi
2. Ubah versi database dan migrasi
3. Backup/Restore database
4. Lakukan migrasi
5. Salin folder desa (kecuali desa/config dan version.json) ke contoh-desa
6. Update catatan rilis
7. Buat contoh contoh_data_awal_20201101.sql
=> rilis v20.11

donjo-app/views/dpt/dpt.php, donjo-app/views/statistik/dpt.php, themes/klasik/partials/wilayah.php
Solusi untuk {perbaikan|fitur baru} terkait issue #3721
=> Sebutan dusun pd dpt, wilayah

donjo-app/config/routes.php, donjo-app/controllers/First.php, donjo-app/controllers/Menu.php, donjo-app/core/MY_Model.php, donjo-app/models/First_artikel_m.php, donjo-app/models/First_menu_m.php, donjo-app/models/Referensi_model.php, donjo-app/models/Web_artikel_model.php, donjo-app/models/Web_kategori_model.php, donjo-app/models/Web_menu_model.php, donjo-app/views/menu/ajax_add_sub_menu_form.php, donjo-app/views/menu/form.php, donjo-app/views/widgets/keuangan.php, donjo-app/views/widgets/menu_kategori.php, themes/hadakewa/partials/content.php, themes/klasik/partials/artikel.php, themes/klasik/partials/content.php, themes/klasik/partials/menu.left.php
1. Tambahkan pilihan jenis link > kategori artikel
2. Tambahkan required pd masing2 jenis link agar tdk terisi kosong
3. Gunakan helper jecho
Solusi untuk {perbaikan|fitur baru} terkait issue #2097
TODO : 
1. Gunakan/sederhanakan 1 view form dan data pd modul menu untuk tipe menu(parrent) dan submenu.
=> Menu Kategori Artikel

donjo-app/controllers/Mandiri_web.php, donjo-app/controllers/Penduduk.php
Solusi untuk {perbaikan|fitur baru} terkait issue  #3726
=> Perbaikan Cetak Biodata Penduduk

donjo-app/controllers/First.php, themes/klasik/partials/wilayah.php
tampilkan jumlah rw menu statis #3722
=> add: tambahkan jumlah rw menu statis

donjo-app/models/Rtm_model.php
Solusi untuk {perbaikan|fitur baru} terkait issue #3740
=> Susulan : Perbaikan kode wilayah pd pembuatan no rtm di modul RTM

assets/js/script.js, donjo-app/controllers/Surat.php, donjo-app/models/Surat_model.php, donjo-app/models/migrations/Migrasi_2011_ke_2012.php, donjo-app/views/surat/form/tgl_berlaku.php, donjo-app/views/surat_master/form.php, template-surat/raw/form.raw
Menentukan nilai default masa berlaku surat issue #1763
=> Menentukan nilai default masa berlaku surat

donjo-app/controllers/Surat_master.php, donjo-app/models/Lapor_model.php, donjo-app/views/surat_master/form.php
Solusi untuk {perbaikan|fitur baru} terkait issue #3735
PERBAIKAN :
1. Syarat surat boleh kosong
2. Hapus syrat surat pd database jika tidak disedikan di layanan mandiri
=> #3735 Syarat surat boleh kosong

donjo-app/views/feed.php
Solusi untuk {perbaikan|fitur baru} terkait issue #3755
=> #3755 Feed.php

donjo-app/helpers/opensid_helper.php, donjo-app/models/Setting_model.php, donjo-app/models/Track_model.php, donjo-app/models/migrations/Migrasi_2011_ke_2012.php
=> Pengaturan Token TrackSID

donjo-app/controllers/Sitemap.php, donjo-app/views/sitemap.php
Solusi untuk perbaikan terkait issue #3758
=> #3758 - Fix sitemap.xml mengalami error

donjo-app/views/statistik/dpt.php, themes/hadakewa/css/first.css, themes/klasik/css/first.css
Solusi untuk {perbaikan|fitur baru} terkait issue #3781
=> Susulan PR #3729

catatan_rilis_20.12.txt, contoh_data_awal_20201201.sql, donjo-app/helpers/opensid_helper.php, donjo-app/models/Database_model.php
=> Rilis v20.12

desa-contoh/css/hadakewa/desa-web.css, desa-contoh/css/klasik/desa-web.css, themes/hadakewa/css/first.css, themes/klasik/css/first.css
Solusi untuk perbaikan terkait issue #3762
=> fix: perbaiki style judul artikel

donjo-app/controllers/First.php, donjo-app/controllers/Lapor_web.php, donjo-app/controllers/Mailbox_web.php, donjo-app/controllers/Mandiri_web.php, donjo-app/views/header.php
Solusi untuk {perbaikan|fitur baru} terkait PR #3652
=> Susulan PR #3652

donjo-app/models/Permohonan_surat_model.php
Solusi untuk {perbaikan|fitur baru} terkait issue #3798
Karena sekarang syrat surat bisa dikosongkan maka perlu dibuatkan kondisi agar tdk selalu mengecek syarat surat (skip jika syarat surat kosong).
=> Susulan Perbaikan

donjo-app/models/Surat_model.php
Solusi untuk perbaikan issue #3804
=> #3804 - Hapus addslashes pada nama penduduk

donjo-app/models/Penduduk_model.php
Solusi untuk perbaikan terkait issue #3805
=> #3805 - Statistik jumlah & total kepemilikan ktp

donjo-app/views/sid/kependudukan/penduduk_form_isian_bersama.php
Solusi untuk {perbaikan|fitur baru} terkait issue #3715
Isian data yg diperlukan sesuai dengan isian data yg ada di Kartu Keluarga.
=> Tambahkan required

donjo-app/controllers/Data_persil.php, donjo-app/models/Data_persil_model.php, donjo-app/views/data_persil/persil.php
- Penambahan Fitur untuk memfilter data pada tabel persil
- Sesuaikan indentasi
Solusi untuk fitur baru terkait issue #3550
=> Penambahan Fitur Filter Data Daftar Persil

donjo-app/controllers/Mailbox_web.php, donjo-app/controllers/Mandiri_web.php, donjo-app/controllers/Permohonan_surat.php, donjo-app/controllers/Setting.php, donjo-app/helpers/opensid_helper.php, donjo-app/models/Database_model.php, donjo-app/models/Setting_model.php, donjo-app/models/Web_widget_model.php, donjo-app/models/migrations/Migrasi_2012_ke_2101.php, donjo-app/views/widgets/layanan_mandiri.php, themes/natra/widgets/layanan_mandiri.php
Solusi untuk {perbaikan|fitur baru} terkait issue #3808
=> Aktif/Nonaktif Layanan Mandiri

donjo-app/controllers/Suplemen.php, donjo-app/views/suplemen/cetak.php
- Perbaikan Script agar Kop Dokumen selalu huruf besar
- Rubah script cetak menggunakan format cetak global
Solusi untuk perbaikan terkait issue #3826
=> Perbaikan Dokumen UNDUH Data Suplemen

donjo-app/controllers/Database.php, donjo-app/helpers/opensid_helper.php, donjo-app/models/Export_model.php, donjo-app/models/Penduduk_model.php
Solusi untuk {perbaikan|fitur baru} terkait issue https://github.com/OpenSID/OpenDK/issues/9
PERBAIKAN:
1. Sertakan Foto penduduk
2. Beri nama foto penduduk berdasarkan NIK, jika NIK = 0 maka nama foto adalah 0 + angka random.
=> Export data penduduk u/ OpenDK

donjo-app/controllers/Inventaris_asset.php, donjo-app/controllers/Inventaris_gedung.php, donjo-app/controllers/Inventaris_jalan.php, donjo-app/controllers/Inventaris_kontruksi.php, donjo-app/controllers/Inventaris_peralatan.php, donjo-app/controllers/Inventaris_tanah.php, donjo-app/helpers/opensid_helper.php, donjo-app/views/inventaris/asset/edit_inventaris.php, donjo-app/views/inventaris/asset/form_tambah.php, donjo-app/views/inventaris/gedung/edit_inventaris.php, donjo-app/views/inventaris/gedung/form_tambah.php, donjo-app/views/inventaris/jalan/edit_inventaris.php, donjo-app/views/inventaris/jalan/form_tambah.php, donjo-app/views/inventaris/peralatan/edit_inventaris.php, donjo-app/views/inventaris/peralatan/form_tambah.php, donjo-app/views/inventaris/tanah/edit_inventaris.php, donjo-app/views/inventaris/tanah/form_tambah.php
1. Sesuaikan kode wilayah
2. Perbaikan indentation
3. Hapus style="100%", gunakan style css yg sdah ada
4. Gunakan $this->header;
Solusi untuk {perbaikan|fitur baru} terkait issue #3825
1. Gabungakan fuction tambah dan edit serta view masing2 inverntaris seperti di modul lainnya (?)
=> #3825 Sesuaikan ulang kode wilayah pada modul inventaris

donjo-app/models/Import_model.php
- Perbaikan Import file `.xlsm`
Susulan PR #3836
=> Susulan PR #3836

donjo-app/controllers/Database.php, donjo-app/models/Export_model.php
Tambahkan Kode_desa dan Tahun di File Export ke OpenDK
=> Tambahkan Kode_desa dan Tahun di File Export ke OpenDK

htaccess.txt
Force HTTPS, agar tidak setting manual di tiap-tiap cPanel
Solusi untuk menggunakan https terkait keamanan dan kenyamanan.
=> Update htaccess.txt (force https)

donjo-app/models/User_model.php
- Gunakan Format session CI
Solusi untuk {perbaikan|fitur baru} terkait issue #3707
=> Perbaikan Pencatatan waktu user login

donjo-app/controllers/Surat_keluar.php, donjo-app/models/Surat_keluar_model.php, donjo-app/views/surat_keluar/form.php, donjo-app/views/surat_keluar/table.php
Tambahkan tombol Bersihkan
Ganti format session ke CI
Solusi untuk perbaikan terkait issue #3845
=> Perbaikan validasi  pada Kode Klasifikasi surat keluar

donjo-app/views/identitas_desa/index.php
Susulan PR mengenai kode wilayah
=> Susulan PR : view kode wilayah identitas desa

donjo-app/models/Inventaris_asset_model.php, donjo-app/models/Inventaris_gedung_model.php, donjo-app/models/Inventaris_jalan_model.php, donjo-app/models/Inventaris_peralatan_model.php, donjo-app/models/Inventaris_tanah_model.php, donjo-app/views/inventaris/asset/table.php, donjo-app/views/inventaris/asset/table_mutasi.php, donjo-app/views/inventaris/gedung/table.php, donjo-app/views/inventaris/gedung/table_mutasi.php, donjo-app/views/inventaris/jalan/table.php, donjo-app/views/inventaris/jalan/table_mutasi.php, donjo-app/views/inventaris/peralatan/table.php, donjo-app/views/inventaris/peralatan/table_mutasi.php, donjo-app/views/inventaris/tanah/table.php, donjo-app/views/inventaris/tanah/table_mutasi.php
Solusi untuk {perbaikan} terkait issue {#3848}
=> #3848 Cantumkan Kode Barang di Tabel

donjo-app/views/inventaris/kontruksi/table.php
Solusi untuk {perbaikan} terkait issue {#3904}
=> #3904 Munculkan Luas Data Inventaris Kontruksi

donjo-app/models/User_model.php
Solusi untuk munculkan Menu Buku Administrasi di Level Operator terkait issue {#3890 }
dan rapikan beberapa baris script.
=> #3890 Menu Buku Administrasi di Level Operator

donjo-app/models/Penduduk_model.php
Solusi untuk penambahan list SHDK terkait issue {#3893}
=> #3893 Tambah SHDK Anak bagi KK (P) yg blm menikah

donjo-app/views/man_user/manajemen_user_form.php
Solusi untuk tidak bisa ubah Level dari Administrator terkait issue {#3891}
=> #3891 Bisa ubah Level dr Administrator selain ID 1

donjo-app/controllers/Permohonan_surat_admin.php
Solusi untuk {perbaikan|fitur baru} terkait issue #3878
=> #3878 : Perbaiki masa berlaku pd permohonan surat layanan mandiri

themes/klasik/layouts/header.php
Solusi untuk {perbaikan|fitur baru} terkait issue #3922
=> #3922 Hapus script.js untuk tema klasik

donjo-app/helpers/opensid_helper.php
Solusi untuk {perbaikan|fitur baru} terkait issue {#3958}
=> Update Format Bawaan BIP 2016

assets/js/peta.js
Perbaiki kesalahan pemuatan data kasus covid-19 di halaman peta pada laman web.
=> Ganti tautan sumber untuk menampilkan data kasus covid-19 di Indonesia

donjo-app/views/sid/wilayah/maps_wilayah.php
Solusi untuk perbaikan terkait issue #4039
=> Perbaiki duplikasi tombol cetak peta

donjo-app/controllers/Mandiri_web.php, donjo-app/core/MY_Controller.php
Solusi untuk {perbaikan|fitur baru} terkait issue #4043
Masalah ini sudah diperbaiki di layanan mandiri pd versi premium
=> sesuaiakan $header layanan mandiri

donjo-app/models/Surat_master_model.php
Solusi untuk {perbaikan|fitur baru} terkait issue #4078
=> #4078 : Pengaturan Surat Layanan Mandiri

donjo-app/controllers/First.php
Solusi untuk {perbaikan} status IDM Tahun 2021
=> Ubah Tahun IDM ke 2021

donjo-app/views/header.php
Solusi untuk {perbaikan|fitur baru} terkait issue https://github.com/OpenSID/OpenSID/issues/4357
=> Pengaturan khusus pelanggan

donjo-app/controllers/Mandiri_web.php
Solusi untuk {perbaikan|fitur baru} terkait issue https://github.com/OpenSID/OpenSID/issues/4348
Untuk view di layanan mandiri versi rilis umum tdk dapat sy sembunyikan.
=> Batasi cetak kk untuk penduduk lepas

donjo-app/controllers/Permohonan_surat.php
Solusi untuk {perbaikan|fitur baru} terkait issue https://github.com/OpenSID/OpenSID/issues/4373
=> Hapus duplikasi
